=== kbaird/Fate-XSLT/characters/FateCore/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, professions?, skills?, languages?,
                     extras?, stunts, consequences?, hacks?, phase-trio, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
      <!ATTLIST refresh base        CDATA #IMPLIED>
      <!ATTLIST refresh current     CDATA #IMPLIED>
      <!ATTLIST refresh free-stunts CDATA #IMPLIED>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type      CDATA #IMPLIED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT professions (profession*)>
      <!ELEMENT profession (#PCDATA)>
      <!ATTLIST profession name   CDATA #REQUIRED>
      <!ATTLIST profession rating CDATA #REQUIRED>

    <!ELEMENT skills (mode*, skill*)>
    <!ATTLIST skills shape (flat|pyramid) "pyramid">
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra name CDATA #IMPLIED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ELEMENT function (#PCDATA)>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions    (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption    (true|false) "false"> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks skill-modes   (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks wealth-boosts CDATA #IMPLIED>       <!-- Baroque Space Opera     -->
      <!ATTLIST hacks wealth-stress (true|false) "false"> <!-- Baroque Space Opera     -->
      <!ATTLIST hacks stress-base-count CDATA #IMPLIED>

    <!ELEMENT phase-trio (phase*)>
      <!ELEMENT phase (events*)>
        <!ATTLIST phase num   CDATA #REQUIRED>
        <!ATTLIST phase title CDATA #IMPLIED>
        <!ELEMENT events (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TianxiaAccelerated/po.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Po, the Dragon Warrior</charname>
    <playername>天下 Accelerated</playername>
    <description>
      Kind of sounds like Jack Black
    </description>
  </id>
  <refresh base="4"/>
  <aspects>
    <aspect type="High-Concept">The Dragon Warrior</aspect>
    <aspect type="Trouble">Complex Relationships with Father Figures</aspect>
    <aspect>Dreaming of Heroics Since Childhood</aspect>
    <aspect>Eager to Self-Improve</aspect>
    <aspect>Shīfu-Spotter</aspect>
  </aspects>
  <skills shape="flat">
    <skill rating="0" name="Careful"/>
    <skill rating="2" name="Clever"/>
    <skill rating="4" name="Flashy"/>
    <skill rating="3" name="Forceful"/>
    <skill rating="1" name="Quick"/>
    <skill rating="1" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="2" name="Storm Dragon 武術" notes="Flashy, Forceful">
      <benefits>
        <benefit name="technique1">details</benefit>
        <benefit name="technique2">details</benefit>
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="stunt1">details</stunt>
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="4"/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/sparrow2.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Sparrow II</charname>
    <playername>&#160;</playername>
    <affiliation>Section 13</affiliation>
    <description>
Daughter of Sparrow I, one of the few Sparrows to inherit the role while the
previous Sparrow was still able-bodied, and the first Sparrow to benefit from
the larger intelligence capability of Section 13. Sparrow II first encountered
Atomic Robo while attempting to thwart Dr. Vanadis Valkyrieâ€™s plot to begin
World War 3 in 1968. She retired to head of Section 13 in 1995.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept" signature="true">Britain's Top Agent</aspect>
    <aspect type="Mode" mode-name="Action">Mistress of the Martial Arts</aspect>
    <aspect type="Mode" mode-name="Science">A Keen and Inquisitive Mind</aspect>
    <aspect type="Mode" mode-name="Banter">Rapier-Sharp Wit</aspect>
    <aspect type="Omega">Underestimate Me At Your Peril</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Action" stress-type="physical"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1" add="2"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="2" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Chemistry"            add="1"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <mode rating="1" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2" add="1"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1"/>
      <skill name="Will"     cost="1"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Judo Black Belt">
      When defending with Combat, on a success with style you may spend a fate point to deal a
      3-shift physical hit to the attacker (instead of getting a boost).
    </stunt>
    <stunt name="Sword Umbrella" mega="true">
      You often carry an umbrella that secretly serves as a sheath for a hidden and slender
      sword blade. It's the 60s; none of this is quite as ridiculous as it sounds. The sword
      has Weapon:2
    </stunt>
    <stunt name="Beauty And The Blade">
      +2 to attack or create an advantage with Combat when wielding a sword.
    </stunt>
    <stunt name="Wreckless Driver">
      Once per scene, when driving a car, you can reduce the harm dealt by an attack by up to 4
      shifts by letting the attacker have a situation aspect with one free invocation.
    </stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/akako_hattori.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Akako Hattori</charname>
    <playername>NPC</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">H.A.T.E. Detective?</aspect>
    <aspect type="Trouble">Not a Lateral Thinker â†’  You're Better Than This?</aspect>
    <aspect>Diligent, But Not Corrupt</aspect>
    <aspect></aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Investigate?"/>

    <skill rating="3" name="Empathy?"/>
    <skill rating="3" name="Contacts?"/>

    <skill rating="2" name="&#160;"/>
    <skill rating="2" name="&#160;"/>
    <skill rating="2" name="Shoot?"/>

    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
  </skills>
  <languages>
  </languages>
  <extras>
  </extras>
  <stunts>
    <stunt name="">&#160;</stunt>
    <stunt name="">&#160;</stunt>
    <stunt name="">&#160;</stunt>
  </stunts>
  <consequences/>
  <phase-trio/>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/margrethe_jarlov.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>Margrethe Jarlov</charname>
    <playername>NPC</playername>
    <description>Played by comedienne Jen Kirkman</description>
    <homeworld name="Fathom" ref="FH 8" habituated-gravity="?" tech-index="7"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Kirsten Gillibrand meets Beto O'Rourke</aspect>
    <aspect type="Trouble">Let Me Study That and Get Back to You</aspect>
    <aspect type="Motivation">Establish Myself as a Well-Connected Politician</aspect>
    <aspect type="Instinct">Don't Rock the Boat</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Empathy"/>

    <skill rating="3" name="Contacts"/>
    <skill rating="3" name="Will"/>

    <skill rating="2" name="Knowledge"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Resources"/>

    <skill rating="1" name="Bureaucracy"/>
    <skill rating="1" name="Empathy"/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes>
    The most generically "moderate" candidate for Far Havens Senator.

    Inspirational to some voters, but never in a policy-specific way. Broadly inoffensive, but also
    considered a bit of a lightweight. A "compromise" candidate in all senses of the term.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/TimeWatch/green_eye.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Green Eye</charname>
    <playername>Morgan Baird</playername>
    <description>&#160;</description>
  </id>
  <aspects>
    <aspect type="High-Concept">Cyborg Meerkat Archaeologist</aspect>
    <aspect type="Trouble"></aspect>
    <aspect phase-num="1"></aspect>
    <aspect phase-num="2"></aspect>
    <aspect phase-num="3"></aspect>
  </aspects>
  <professions>
    <profession rating="2" name="Adventurer"/>
    <profession rating="1" name="Burglar"/>
    <profession rating="0" name="Chit-Chat"/>
    <profession rating="3" name="Historian"/>
    <profession rating="1" name="Scientist"/>
    <profession rating="2" name="Soldier"/>
  </professions>
  <extras>
  </extras>
  <stunts>
  </stunts>
  <consequences>
  </consequences>
  <hacks stress-base-count="3"/>
  <phase-trio>
    <phase num="1">
      <events>Some events</events>
    </phase>
    <phase num="2">
      <events>Some events</events>
    </phase>
    <phase num="3">
      <events>Some events</events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/kung_fu_trucker.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Kung Fu Trucker</charname>
    <playername>NPC</playername>
    <affiliation>Deadly Disco Комиссар</affiliation>
    <description>
    &#160;
  </description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Kung Fu Trucker</aspect>
    <aspect type="Mode" mode-name="Martial&#160;Artist">Fists of Fury</aspect>
    <aspect type="Mode" mode-name="Trucker">Breaker, Break Her (Him, It)</aspect>
    <aspect type="Mode" mode-name="Action">Greased Lightning</aspect>
    <aspect type="Omega"/>
  </aspects>
  <skills>
    <mode rating="3" name="Martial&#160;Artist" stress-type="physical">
      <!-- ARRPG pg88 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Stealth" cost="2"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="2" name="Trucker" stress-type="physical">
      <!-- Fighter Pilot, ARRPG pg296 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Vehicles" cost="2" add="1"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="1" name="Action">
      <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Provoke" cost="1"/>
      <skill name="Vehicles" cost="2"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Blind-Fight">Your ability to attack with Combat works unimpeded by conditions like darkness or other visual impairments.</stunt>
    <stunt name="Fist of Death">By concentrating your force into a powerful blow, you may devastate even the most potent of opponents. Once per opponent per fight, you may spend a fate point after landing a successful blow to cause your opponent to check their highest unchecked physical stress box (instead of taking stress equal to the shifts you succeeded by).</stunt>
    <stunt name="Leave My Friends Alone!">+2 to attack with Fight when your opponent’s most recent action was to attack one of your allies.</stunt>
    <stunt name="Riposte">If you succeed with style on a Combat defense, you can choose to inflict a 2-shift hit rather than take a boost.</stunt>
    <stunt name="Stunning Fist: ☐ ">Once per physical conflict, when you succeed on an unarmed attack, you may place the aspect Stunned on your opponent with one free invocation.</stunt>
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/zird_with_professions.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Zird the Arcane</charname>
    <playername>sample Fate Core character</playername>
    <description>A sharp-featured scholar with a dark triangular beard.</description>
  </id>
  <refresh>2</refresh>
  <current-fate-points>2</current-fate-points>
  <aspects>
    <aspect type="High-Concept">Wizard for Hire</aspect>
    <aspect type="Trouble">Rivals in the Collegia Arcana</aspect>
    <aspect phase-num="1">If I Haven't Been There, I've Read About It</aspect>
    <aspect phase-num="2">Not The Face!</aspect>
    <aspect phase-num="3">Doesn't Suffer Fools Gladly</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Fighter"/>
    <profession rating="3" name="Scholar"/>
    <profession rating="0" name="Woodsman"/>
    <profession rating="1" name="Thief"/>
    <profession rating="2" name="Craftsman"/>
    <profession rating="2" name="Diplomat"/>
  </professions>
  <extras>
    <extra name="Collegia Arcana Mage">
      Allows the use of Scholar for loosely-defined magical actions.
    </extra>
  </extras>
  <stunts>
    <stunt name="Scholar, Healer">
    Can make Physical Recovery attempts w/Scholar
  </stunt>
    <stunt name="The Power of Deduction">
    Once per scene you can spend a fate point (and a few minutes of observation) to make a
    special Scholar roll representing your potent deductive faculties. For each shift
    you make on this roll you discover or create an aspect, on either the scene or the target
    of your observations, though you may only invoke one of them for free.
  </stunt>
    <stunt name="I've Read About That!">
    You’ve read hundreds—if not thousands—of books on a wide variety of topics. You can spend
    a fate point to use Scholar in place of any other skill for one roll or exchange, provided
    you can justify having read about the action you’re attempting.
  </stunt>
  </stunts>
  <consequences>
    <consequence severity="Mild">mild one</consequence>
  </consequences>
  <hacks stress-base-count="3"/>
  <phase-trio>
    <phase num="1">
      <events>Some events</events>
    </phase>
    <phase num="2">
      <events>Some events</events>
    </phase>
    <phase num="3">
      <events>Some events</events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/courtney_pc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>&#160;</charname>
    <playername>Courtney Irving</playername>
    <story>
      Comes from a nouveau riche family that owns a company that manufactures
      Jade-powered drones and (somewhat quizzically) employs Mike's alchemist PC.
      Probably travels in similar social circles to Jenn's PC.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">&#160;</aspect>
    <aspect type="Background">&#160;</aspect>
    <aspect type="Inciting-Incident">&#160;</aspect>
    <aspect type="Belief">&#160;</aspect>
    <aspect type="Trouble">&#160;</aspect>
  </aspects>
  <professions>
    <profession rating="&#160;" name="Aristocrat"/>
    <profession rating="3" name="Engineer"/>
    <profession rating="&#160;" name="Explorer"/>
    <profession rating="&#160;" name="Fighter"/>
    <profession rating="&#160;" name="Scholar"/>
    <profession rating="&#160;" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Drone Specialist" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" profession="Engineer" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when working on Jade-powered drones"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>
