=== kbaird/Fate-XSLT/characters/FateCore/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, professions?, skills?, languages?,
                     extras?, stunts, consequences?, hacks?, phase-trio, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
      <!ATTLIST refresh base        CDATA #IMPLIED>
      <!ATTLIST refresh current     CDATA #IMPLIED>
      <!ATTLIST refresh free-stunts CDATA #IMPLIED>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type      CDATA #IMPLIED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT professions (profession*)>
      <!ELEMENT profession (#PCDATA)>
      <!ATTLIST profession name   CDATA #REQUIRED>
      <!ATTLIST profession rating CDATA #REQUIRED>

    <!ELEMENT skills (mode*, skill*)>
    <!ATTLIST skills shape (flat|pyramid) "pyramid">
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra name CDATA #IMPLIED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ELEMENT function (#PCDATA)>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions    (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption    (true|false) "false"> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks skill-modes   (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks wealth-boosts CDATA #IMPLIED>       <!-- Baroque Space Opera     -->
      <!ATTLIST hacks wealth-stress (true|false) "false"> <!-- Baroque Space Opera     -->
      <!ATTLIST hacks stress-base-count CDATA #IMPLIED>

    <!ELEMENT phase-trio (phase*)>
      <!ELEMENT phase (events*)>
        <!ATTLIST phase num   CDATA #REQUIRED>
        <!ATTLIST phase title CDATA #IMPLIED>
        <!ELEMENT events (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Ravenloft/alexa_sarandon.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Alexa Sarandon</charname>
    <playername>sample Weird World News character</playername>
    <description>&#160;</description>
  </id>
  <aspects>
    <aspect type="High-Concept">Fame-Obsessed Anchorwoman</aspect>
    <aspect type="Trouble">Must Find the Perfect Camera Angle</aspect>
    <aspect type="Motivation">I Will Make WWN The Top Channel!</aspect>
  </aspects>
  <skills name="Aptitudes" shape="flat">
    <skill rating="4" name="Bamboozle!"/>
    <skill rating="3" name="Entrap!"/>
    <skill rating="2" name="Investigate!"/>
    <skill rating="1" name="Run!"/>
  </skills>
  <stunts>
    <stunt name="Trapmaster">blah</stunt>
  </stunts>
  <hacks conditions="wwn" single-stress-track="true" stress-base-count="3"/>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/susan.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Susan</charname>
    <playername>Phil Bernard</playername>
    <description>
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Energy Leech - NOT a Vampire</aspect>
    <aspect type="Trouble">Juicing Makes Me Feel Alive</aspect>
    <aspect phase-num="1">I Am Not A Monster, I Can Control This</aspect>
    <aspect phase-num="2">We're All Worth Saving</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Physique"/>

    <skill rating="3" name="Deceive"/>
    <skill rating="3" name="Fight"/>

    <skill rating="2" name="Notice"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Stealth"/>

    <skill rating="1" name="Athletics"/>
    <skill rating="1" name="Drive"/>
    <skill rating="1" name="Empathy"/>
    <skill rating="1" name="Will"/>
  </skills>
  <languages>
  </languages>
  <extras>
  </extras>
  <stunts>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
      </events>
    </phase>
    <phase num="2">
      <events>
        Susan is a waitress who works with Darcy. Saw her use new powers to escape attacker,
        tried to knock him out but killed him.
      </events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/TianxiaAccelerated/detective_dishi.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Detective Dishi</charname>
    <playername>Tianxia Accelerated</playername>
    <description>
      Lanky and vaguely awkward looking, Detective Dishi nevertheless might be the greatest force
      for justice in Băo Jiāng. A junior magistrate whose unwillingness to take bribes or look the
      other way when crimes are committed by the wealthy or powerful, this young man has already
      made a lot of enemies. He also has a few friends, a mix of soldiers, merchants, and local
      luminaries who help keep Dishi from catching a dagger in the back. Dishi favors nonlethal
      methods, but when called on to defend himself he wields his iron judge’s pen and reinforced
      fan with skill and enthusiasm.
    </description>
  </id>
  <refresh base="4"/>
  <aspects>
    <aspect type="High-Concept">One Good Cop in a Bad Town</aspect>
    <aspect type="Trouble">Problem With Authority</aspect>
    <aspect>Băo Jiāng's Greatest Detective</aspect>
    <aspect>Never Gives Up</aspect>
    <aspect>Unconventional Methods</aspect>
  </aspects>
  <skills name="Approaches" shape="flat">
    <skill rating="3" name="Careful"/>
    <skill rating="4" name="Clever"/>
    <skill rating="1" name="Flashy"/>
    <skill rating="0" name="Forceful"/>
    <skill rating="2" name="Quick"/>
    <skill rating="1" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="2" name="Stone Crane 武術" notes="Careful, Clever">
      <benefits>
        <benefit name="Crane Hides in Reeds">
          Add a +2 bonus with using Full Defense to defend yourself. If defending others, gain
          2 Armor Rating against the attack instead.
        </benefit>
        <benefit name="Crane Stuns the Carp">
          If you succeed on a Careful of Clever physical attack with style, you may create a
          Stunned advantage on a target with a free invocation instead of taking a bonus.
        </benefit>
        <benefit name="Stone Resists the Blow">
          You gain 2 Armor against any physical attack you are aware of.
        </benefit>
        <!--
        <benefit name="江湖 (jiānghú) Rank 1: ☐">
          1 Free Invocation of Chi Armor per conflict.
          Automatically succeed on a Recover action for a Consequence if allowed to quietly meditate.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 2: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May grant Chi Armor or Consequence recovery to others.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 3: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May recover a Moderate Consequence in half the time by reducing Chi Armor invocations per conflict back down to 1.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 4">
          May recover a Severe Consequence as above.
          Chi Armor now gives 3 Armor Rating instead of 2.
        </benefit>
        -->
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="Burden of Proof">
      Use Clever instead of Forceful to intimidate, frighten, or cower those you have
      incriminating evidence against.
    </stunt>
    <stunt name="Elementary!">
      +2 on Clever Overcome rolls based on investigation and detective work.
    </stunt>
    <stunt name="Just the Facts">
      Do not grant a free invoke to an opponent when failing to use Clever to Create an
      Advantage based on intuition or deception.
    </stunt>
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="3"/>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/nima_shirazi.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Nima Shirazi</charname>
    <playername>Kevin Baird</playername>
    <description>
      Originally an Iranian-American computer scientist and roboticist from Orange County, CA.
      After contracting a terminal illness, successfully transferred consciousness into a small
      (5ish) cadre of robotic insectoid bodies. Given the economics of micro-electronics
      manufacturing, he's now mostly Chinese.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Brilliant Transhumanist Visionary</aspect>
    <aspect type="Trouble">Strahd Will Pay</aspect>
    <aspect phase-num="1">Ghostcomp in Multiple Insectoid Cybershells</aspect>
    <aspect phase-num="2">Nima Knows</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <!--
    Want
      Lore
      Notice
      Rapport
      X Hacking
      Stealth
      X Will

    Do Not Want
      Contacts
      Drive
      Fight
      Physique
      Shoot

    Not Sure
      Athletics
      Burglary
      Crafts
      Deceive
      Empathy
      Investigate
      Provoke

    -->
    <skill rating="4" name="Hacking"/>

    <skill rating="3" name="&#160;"/>
    <skill rating="3" name="Will"/>

    <skill rating="2" name="&#160;"/>
    <skill rating="2" name="&#160;"/>
    <skill rating="2" name="&#160;"/>

    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
  </skills>
  <languages>
    Speaks English and Farsi natively. Probably a smattering of Arabic.
    He's probably enough of a douche to want to speak French just because.
  </languages>
  <extras>
    <gadget name="Uruk Systems" cost="1">
      <function>Billion-Dollar Bio- and Info-Tech Company</function>
      <flaws>
        <flaw>Gotta Keep the Public and Shareholders Happy</flaw>
        <flaw>High Profile; Easy to Find</flaw>
      </flaws>
      <aspects>
        <aspect>Intrusion Countermeasures Against Vampires and Other Threats</aspect>
        <aspect>Bringing Tomorrow's Technology to the Public</aspect>
        <aspect>Adnan the Robot Butler</aspect>
        <aspect>Very Smart People Work Here</aspect>
      </aspects>
      <benefits>
        <benefit name="Prototypes ☐ ☐">
          A team of roboticists is constantly tinkering with the features of his robot bodies.
          Twice per session, can declare an Aspect with a free Invocation to represent that. (T:SBS, pg48)
        </benefit>
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="Attention to Detail">
      You can use Investigate instead of Empathy to defend against Deceive attempts. What others discover
      through gut reactions and intuition, you learn through careful observation of microexpressions.
    </stunt>
    <stunt name="Body Language Reader">
      You can use Notice in place of Empathy to learn the aspects of a target through observation.
    </stunt>
    <stunt name="Drinks the Kool-Aid">
      May use Rapport instead of Deceive to Overcome when
      he believes he's ultimately doing the right thing.
    </stunt>
    <stunt name="No, YOU Move">
      When you use Will to Defend against fear or intimidation, on a Success With Style
      instead of gaining a Boost you can inflict a 2-shift mental hit on the attacker.
      (M12, pg42)
    </stunt>
    <stunt name="Revenge Is A Dish Best Served By Infomorphs, You Murderous Undead Bloodsucker">
      Gain a +3 bonus instead of +2 when Invoking Strahd Will Pay.
    </stunt>
    <stunt name="Robot Bodies Make No Cortisol">
      Immune to attempts to Create Advantages describing emotional states more extreme than cool, rational ones.
    </stunt>
    <stunt name="Seen It All">
      Armor: 2 vs. mental attacks (M12, pg25)
    </stunt>
    <stunt name="Smartlinks">
      May use Hacking to Attack when invoking Aspects describing computer-controller weapons.
    </stunt>
    <stunt name="Standing On the Shoulders of Van Helsing">
      +2 to Create (recall) an Advantage with Lore directly pertaining to vampirism.
    </stunt>
    <stunt name="Xanatos Speed Chess ☐">
      Once per Session, after failing to Overcome vs. the Big Bad, rename one Situation Aspect already
      in play, representing your ability to shift long-term plans to account for new developments.
    </stunt>
    <!--
    <stunt name="Careful Shot">
      When you take time to aim for an exchange prior to shooting, you may use
      Survival to Attack instead of Shoot. (AA, pg119)
    </stunt>
    -->
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
        Contracted a terminal illness, sailed to international waters for a destructive braintaping
        with Darcy's help. Sometime before that, Strahd vamped his child, who Nima had to kill/put
        down/destroy. The mother is presumed by Nima to have been killed by the child, but he may
        be mistaken.
      </events>
    </phase>
    <phase num="2">
      <events>
        Nima hired a team of lawyers to defend Susan or get her case never to
        come to trial with the understanding that she come work for his team.
      </events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/Banished/fungible_zhou.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname nickname="Zhōu">Fungible 周</charname>
    <playername>Brian Wilcox</playername>
    <description>
      Brick Accountant from the suburbs of the capital; his insistence on
      following rules got in the way of their corruption.
      Exiled to 饱江/Băo Jiāng with the impossible task of reducing graft.
      Tall and wide, but not fat. Bookish, not brutish.

      Followed by 陈达玉/Chén Dá Yù while investigating graft.
      She secretly aided him illegally, but he's too naive to notice.
      Acquired 刘丽华/Liú Lí Huá's statue from Madam 刘/Liú's grandchildren
      in lieu of back taxes.
    </description>
    <unique>刘丽华/Liú Lí Huá's statue is always within 12 feet of me</unique>
  </id>
  <refresh base="4"/>
  <aspects>
    <aspect type="High-Concept">
      Brick Accountant [Descending from Earth Sorcerors]
    </aspect>
    <aspect type="Trouble">
      Exiled [For Standing on Principle]
    </aspect>
    <aspect phase-num="1">
      Blessed with a Cursed Statue
    </aspect>
    <aspect phase-num="2">&#160;</aspect>
    <aspect phase-num="3">&#160;</aspect>
  </aspects>
  <skills name="Approaches" shape="flat">
    <skill rating="3" name="Careful"/>
    <skill rating="2" name="Clever"/>
    <skill rating="1" name="Flashy"/>
    <skill rating="2" name="Forceful"/>
    <skill rating="0" name="Quick"/>
    <skill rating="1" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="1" name="Stone Crane 武術" notes="Careful, Clever:
      One of the most defensively solid styles, Stone
      Crane relies on solid stances and limiting an opponent’s
      ability to attack. Practitioners use blocks, circular
      evasion, locks, and pressure point strikes to avoid
      attacks and hinder opponents. Weaker on attack, Stone
      Crane stylists wait until the right opening and put an
      attacker down hard and fast.">
      <benefits>
        <benefit name="Mountain Does Not Fall">
          You get a +2 bonus to defend against attempts to
          create an advantage based on unbalancing,
          pushing, tripping, or knocking over the
          defender. If a technique from an opponent
          instead allows them to create such an
          advantage with free invocations, one
          less free invocation is granted though the
          advantage is still created.
        </benefit>
        <!--
        <benefit name="Stone Weathers the Storm">
          If you defend with style, you may remove your 1 stress box or
          convert another stress box to 1 lower instead of taking a boost.
        </benefit>
        <benefit name="Poisoned Mirror">
          The exorcist can redirect the
          energies sorcerers throw back to them. Success with
          style on a Defend against a mystical Attack lets the
          character describe turning the Attack back at the
          foe. Instead of generating a boost, inflict 1 stress on
          the attacker which cannot be blocked by any armor.
          Even though sorcerers are immune to Attacks of their
          element, the deflection infuses disruptive energies that
          they cannot ignore.
        </benefit>
        <benefit name="Spirit Commander">
          If the exorcist takes a spirit
          out, instead of banishing it outright, he can force it
          to perform a task before it departs. The supernatural
          being executes the task to the letter, but cannot harm
          or act against the exorcist. Once it completes the task
          or is released from service, it is banished.
          </benefit>
        -->
        <!--
        <benefit name="江湖 (jiānghú) Rank 1: ☐">
          1 Free Invocation of Chi Armor per conflict.
          Automatically succeed on a Recover action for a Consequence if allowed to quietly meditate.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 2: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May grant Chi Armor or Consequence recovery to others.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 3: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May recover a Moderate Consequence in half the time by reducing Chi Armor invocations per conflict back down to 1.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 4">
          May recover a Severe Consequence as above.
          Chi Armor now gives 3 Armor Rating instead of 2.
        </benefit>
        -->
      </benefits>
    </gadget>
    <!--
    <gadget name="Tiny Abacus">
      <function>Drastically speeds up math operations</function>
      <flaws>
        <flaw>Egghead likes his booky-wook</flaw>
      </flaws>
      <benefits>
        <benefit name="It's a Kind of Magic">
          Can notice and defend against magic as if it were mundane
        </benefit>
      </benefits>
    </gadget>
    -->
  </extras>
  <stunts>
    <stunt name="Ripples in the Earth">
      The ground speaks to the
      sorcerer through her feet. She can sense when others
      are approaching as she feels their footsteps, even while
      asleep. The sorcerer can Carefully notice in those situations
      even if others could not and gets a +2 to her Careful
      roll when others could attempt to notice as normal.
      Additionally, by concentrating she can use Clever
      to uncover more information—how many people are
      approaching, what rooms or caverns exist nearby, any
      underground streams, and similar feats of perception.
    </stunt>
    <stunt name="&#160;">
      Because I [describe some way that you are exceptional, have a cool bit
      of gear, or are otherwise awesome], I get a +2 when I
      [pick one: Carefully, Cleverly, Flashily, Forcefully, Quickly, Sneakily]
      [pick one: attack, defend, create advantages, overcome] when
      [describe a circumstance].
    </stunt>
    <!--
    <stunt name="Ally's Shield">
      You can invoke Dwarven Shield-Maiden when a nearby ally suffers an attack.
      When you do, redirect that attack to yourself. Your defense is
      Average (+1) against that attack.
    </stunt>
    <stunt name="Backstab: ☐">
      Because I am Death's silent hand, once per session, when I strike an
      unaware target from hiding, I may require that target to take the hit
      without the benefit of their stress track.
    </stunt>
    <stunt name="Ritualist II: ☐">
      Once per session, when facing a challenge, you may perform a magic ritual
      to automatically succeed with style at any one component task of the challenge.
    </stunt>
    <stunt name="The Lessons of Master Zhao">
      Use [new Approach] instead of [usual Approach] with [specific style of] Kung Fu
    </stunt>
    -->
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="3"/>
  <phase-trio>
    <phase num="1">
      <events>Some events</events>
    </phase>
    <phase num="2">
      <events>Some events</events>
    </phase>
    <phase num="3">
      <events>Some events</events>
    </phase>
  </phase-trio>
  <notes>
    周's dad was a mason, ancestors were Earth Sorcerors, but that has been purged from history.
    When 周 got the statue, it registered as mystical and triggered his woo-woo sight.
    This allowed 周 to also notice that his abacus family heirloom is also magical. Details TBD.
    Some anonymous benefactor paid for 周's tuition to become an accountant.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicShadowrun/dwarf_decker.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Decker</charname>
    <playername>SR5 Quick-Start Rules</playername>
    <description>&#160;</description>
  </id>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Dwarf Decker</aspect>
    <aspect type="Mode" mode-name="Science"></aspect>
    <aspect type="Mode" mode-name="Intrigue"></aspect>
    <aspect type="Mode" mode-name="Action">Tough &amp; Decent with a Pistol</aspect>
    <aspect type="&#937;">Speaks Aztlaner Spanish (expand)</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Hacking"               add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <!--
         Specialize one trained skill. Hacking
         Focus one trained skill.
         Specialize one focused skill.
    -->
    <mode rating="2" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
    </mode>
    <mode rating="1" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
  </skills>
  <stunts>
    <gadget name="Shiawase Cyber-5">
      <function>Cyberdeck</function>
      <flaws>
        <flaw>Illegal and not very concealable</flaw>
      </flaws>
    </gadget>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/tiffani.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Tiffani&#9829;</charname>
    <playername>Courtney Irving</playername>
    <affiliation>Tesladyne Oakland (Action Scientist PC)</affiliation>
    <description>&#160;</description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Terrifying Receptionist</aspect>
    <aspect type="Mode" mode-name="Action">Most Vicious Fighter on the West Coast</aspect>
    <aspect type="Mode" mode-name="Banter">Speaks Her Mind</aspect>
    <aspect type="Mode" mode-name="Intrigue">Sketchy Background, No Last Name</aspect>
    <aspect type="&#937;">You Wouldn't Like Me When I'm Hangry</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1"/>
      <skill name="Will"     cost="1"/>
    </mode>
    <mode rating="1" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
    </mode>
 </skills>
  <stunts>
    <stunt name="Look Into My Eye">
      Use Provoke to defend against threats and other fear-based attacks that deal mental harm.
    </stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
    Still has 1 Minor Milestone (ARRPG225) from stopping the hybrid queen.
    Regardless of what modes you have, if they're all standard modes you get ONE of the following improvements:
    * Specialize one trained skill.
    * Focus one trained skill and specialize one focused skill.
    * Focus three trained skills.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/nigel_gershmann.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>Nigel Gershmann</charname>
    <playername>NPC</playername>
    <description>
      Played by British historian Simon Schama. Wears a Baron Harkonnen-style anti-grav
      harness to get around in normal gravity and has obvious cranial implants.
    </description>
    <homeworld name="Astar planetoids" ref="FH 56" habituated-gravity="micro" tech-index="8"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Highly-Educated Technocrat from the "Old Country"</aspect>
    <aspect type="Trouble">New Enough Arrival to Get Called "Carpetbagger"</aspect>
    <aspect type="Motivation">Expand Fathom's Recognition in the Far Havens</aspect>
    <aspect type="Instinct">Compromise Whenever Necessary On Anything But Land Rights</aspect>
    <aspect>Favors "Old Astar" Values over "New Canopy"</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Contacts"/>

    <skill rating="3" name="Knowledge"/>
    <skill rating="3" name="Resources"/>

    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Science"/>
    <skill rating="2" name="Technical"/>

    <skill rating="1" name="Empathy"/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <extras>
    <extra cost="3" name="HyperIntelligence">
      Gain a +2 bonus to any Knowledge, Science, or Technical roles where reasoning power is the determining factor.
      (Mindjammer pg 109)
    </extra>
  </extras>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes>
    Jenn tells me his appearance and recent arrival from Astar is not especially noteworthy 
    in Canopy. He's just an outlier of a tendency already common to the populace. His age cohort
    probably chuckles behind his back that it took him long enough to emigrate from Astar.
    Shares the communitarian outlook common to Canopy and Astar, presumably inspired by the
    demands of Astar's fully artificial enviornment (like Traveller's Glisten).
  </notes>
</character>
