=== kbaird/Fate-XSLT/characters/FateCore/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, professions?, skills?, languages?,
                     extras?, stunts, consequences?, hacks?, phase-trio, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
      <!ATTLIST refresh base        CDATA #IMPLIED>
      <!ATTLIST refresh current     CDATA #IMPLIED>
      <!ATTLIST refresh free-stunts CDATA #IMPLIED>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type      CDATA #IMPLIED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT professions (profession*)>
      <!ELEMENT profession (#PCDATA)>
      <!ATTLIST profession name   CDATA #REQUIRED>
      <!ATTLIST profession rating CDATA #REQUIRED>

    <!ELEMENT skills (mode*, skill*)>
    <!ATTLIST skills shape (flat|pyramid) "pyramid">
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra name CDATA #IMPLIED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ELEMENT function (#PCDATA)>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions    (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption    (true|false) "false"> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks skill-modes   (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks wealth-boosts CDATA #IMPLIED>       <!-- Baroque Space Opera     -->
      <!ATTLIST hacks wealth-stress (true|false) "false"> <!-- Baroque Space Opera     -->
      <!ATTLIST hacks stress-base-count CDATA #IMPLIED>

    <!ELEMENT phase-trio (phase*)>
      <!ELEMENT phase (events*)>
        <!ATTLIST phase num   CDATA #REQUIRED>
        <!ATTLIST phase title CDATA #IMPLIED>
        <!ELEMENT events (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TimeJanitors/1034_tom.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>1034 Tom</charname>
    <playername>Gus Bernat</playername>
    <description>&#160;</description>
  </id>
  <aspects>
    <aspect type="High-Concept">Cyborg Soldier</aspect>
    <aspect type="Trouble"></aspect>
    <aspect type="Native Timeline"></aspect>
    <aspect></aspect>
    <aspect></aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Adventurer"/>
    <profession rating="1" name="Burglar"/>
    <profession rating="0" name="Chit-Chat"/>
    <profession rating="2" name="Historian"/>
    <profession rating="2" name="Scientist"/>
    <profession rating="3" name="Soldier"/>
  </professions>
  <extras>
  </extras>
  <stunts>
    <stunt name="Cyborg">
      Because I am a cyborg, I can receive radio, TV and similar signals without extra equipment.
    </stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks stress-base-count="3"/>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/speaker_for_the_isolationists.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>"Speaker"</charname>
    <playername>NPC</playername>
    <description>Played by Dame Judi Dench</description>
    <homeworld name="Fathom" ref="FH 8" habituated-gravity="?" tech-index="7"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Speaker for the Canopy Isolationists</aspect>
    <aspect type="Trouble">Xenophobes Ain't Xenoaware</aspect>
    <aspect type="Motivation">We Want Canopy to Deal with Outsiders for Us</aspect>
    <aspect type="Instinct">Let's Get This Conversation Over With</aspect>
    <aspect>I Assume You're Trying to Screw Us Over</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Bureaucracy"/>

    <skill rating="3" name="Provoke"/>
    <skill rating="3" name="Will"/>

    <skill rating="2" name="Deceive"/>
    <skill rating="2" name="Empathy"/>
    <skill rating="2" name="Resources"/>

    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="Esprit de Corps">
      Gain a +2 defend bonus when personnel are acting in solidarity to resist morale attacks or propaganda campaigns.
      (Mindjammer pg 274)
    </stunt>
    <stunt name="Secret Reserves ☐ ☐">
      Nobody knows what tricks the Isolationists have up their collective sleeves.
      Twice per session, can declare an Aspect with a free Invocation to represent that. (Tianxia: Spirits, Beasts, &amp; Spells, pg 48)
    </stunt>
    <stunt name="Stubborn">
      +2 to Attack with Bureaucracy when stonewalling / creating impediments to change.
    </stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TianxiaAccelerated/hong_mo.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname nickname="洪謨">Hóng Mó</charname>
    <playername>Morgan Baird</playername>
    <description>
      11-year-old girl, inspired to leave the Silken Shadows by Chén dá yù's example, who is barely aware of it.
    </description>
    <unique>On a quest to learn the Secret Technique of 气 (Qì) Blocking</unique>
  </id>
  <refresh base="4" free-stunts="1"/>
  <aspects>
    <aspect type="High-Concept">Runaway Orphan; Mostly Reformed Pickpocket</aspect>
    <aspect type="Trouble">&#160;</aspect>
    <aspect phase-num="1">Raised by the Silken Shadow Triad</aspect>
    <aspect phase-num="2">&#160;</aspect>
    <aspect phase-num="3">&#160;</aspect>
  </aspects>
  <skills name="Approaches" shape="flat">
    <skill rating="1" name="Careful"/>
    <skill rating="3" name="Clever"/>
    <skill rating="1" name="Flashy"/>
    <skill rating="0" name="Forceful"/>
    <skill rating="2" name="Quick"/>
    <skill rating="2" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="1" name="Ghost Monkey 武術" notes="Clever, Sneaky:
Ghost Monkey concentrates on the mastery of internal energies to augment the style's acrobatic
defenses and attacks. Pushes, feints, sweeps, and pressure point strikes hinder an attacker, making him
easier to outmaneuver and subdue. Rolls and dodges keep opponents at a distance until the practitioner
can find the right opening to finish the fight with a disabling strike or grapple. One of the most physical of
the Ghost styles, many underestimate the inner power of the capering, mocking Ghost Monkey.">
      <benefits>
        <benefit name="Ghost Haunts the Shadow">
          You may use Clever instead of Sneaky to Create an Advantage based on stealth or concealment. If
          Sneaky is greater or equal to a character's Clever approach, gain a +2 bonus to such rolls instead.
        </benefit>
        <benefit name="Ghost Strikes the Spirit">
          Gain +1 Weapon Rating and ignore 1 Armor Rating when physically attacking a target who is either
          Jianghu Rank 0, part of a mob, or has a consequence based around weakened 气 (Qì) energies.
        </benefit>
        <benefit name="Monkey Rolls Away">
          When invoking an aspect or advantage during a defense roll, gain 2 Armor Rating against the attack if it succeeds.
        </benefit>
        <!--
        <benefit name="江湖 (jiānghú) Rank 1: ☐">
          1 Free Invocation of Chi Armor per conflict.
          Automatically succeed on a Recover action for a Consequence if allowed to quietly meditate.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 2: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May grant Chi Armor or Consequence recovery to others.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 3: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May recover a Moderate Consequence in half the time by reducing Chi Armor invocations per conflict back down to 1.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 4">
          May recover a Severe Consequence as above.
          Chi Armor now gives 3 Armor Rating instead of 2.
        </benefit>
        -->
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="xxx">
      Because I [describe some way that you are exceptional, have a cool bit of gear, or are otherwise awesome],
      I get a +2 when I [pick one: Carefully, Cleverly, Flashily, Forcefully, Quickly, Sneakily]
      [pick one: attack, defend, create advantages, overcome] when [describe a circumstance].
    </stunt>
    <!--
    <stunt name="Qì (气) Blocking: ☐">
      Because I have access to forbidden lore, once per session and at the cost of spending a Fate Point,
      I may automatically Create an Advantage "Paralyzed" on the target.
    </stunt>
    <stunt name="Ally's Shield">
      You can invoke Dwarven Shield-Maiden when a nearby ally suffers an attack. When you do, redirect that attack to yourself. Your defense is Average (+1) against that attack.
    </stunt>
    <stunt name="Ritualist II: ☐">
      Once per session, when facing a challenge, you may perform a magic ritual to automatically succeed with style at any one component task of the challenge.
    </stunt>
    <stunt name="The Lessons of Master Zhao">
      Use [new Approach] instead of [usual Approach] with [specific style of] Kung Fu
    </stunt>
    -->
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="3"/>
  <phase-trio>
    <phase num="1">
      <events>Orphan who grew up in Băo Jiāng</events>
    </phase>
    <phase num="2">
      <events>Some events</events>
    </phase>
    <phase num="3">
      <events>Some events</events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/junior_dinkley.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>Junior Dinkley</charname>
    <playername>Phil Bernard</playername>
    <description>
      Canid Genotype (MJ 40). Son of a side dalliance on the part of a Dinkley boy.
      CEO of DND Enterprises ("Discovery and Development") that consists of just the PCs.
    </description>
    <homeworld name="Kallistan" ref="FH 8/67" habituated-gravity="0.9" tech-index="8"/>
  </id>
  <aspects>
    <aspect type="High-Concept">From Bastard Canid Throwaway to Secret CEO</aspect>
    <aspect type="Trouble">What I Don't Know Might Kill Me</aspect> <!-- responsible for illegal design of Enki -->
    <aspect phase-num="1">I'm Great At Keeping Secrets! wag wag wag</aspect>
    <aspect></aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Science"/>

    <skill rating="3" name="Resources"/>
    <skill rating="3" name="Technical"/>

    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>

    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="Scent Tracking">
      Your sense of smell is far superior to that of humans. You can track and
      recognise people by scent, and gain a +2 bonus on Investigate and Notice
      rolls related to smell. (FH pg 10)
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio>
    <phase num="1">
      <events>
        Rich canid, paid by Dinkley family to stay away from home.
        The Dinkley family owns (among other things) a huge portion of Daedelus Corporation.
        The Dinkleys sponsored the design of Enki, which was crazy illegal due to eschewing
        the Asimov Protocols. Someone is still trying to tie up that loose end.
      </events>
    </phase>
    <phase num="2">
      <events>&#160;</events>
    </phase>
    <phase num="3">
      <events>&#160;</events>
    </phase>
  </phase-trio>
  <notes>
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/jexy.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Jexy</charname>
    <playername>Morgan Baird</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept"></aspect>
    <aspect type="Trouble"></aspect>
    <aspect type="Burdens"></aspect>
    <aspect type="True-Name"></aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name=""/>
    
    <skill rating="3" name=""/>
    <skill rating="3" name=""/>
    
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/luna.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Luna</charname>
    <playername>Eva Doucette</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Neighborhood Peacekeeper (Warden)</aspect>
    <aspect type="Trouble">Too Many Burdens</aspect>
    <aspect type="Burdens">Everyone On My Street</aspect>
    <aspect type="True-Name">Pragmatic Protector</aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Warding"/>
    
    <skill rating="3" name="Alchemy"/>
    <skill rating="3" name="Illusion"/>
    
    <skill rating="2" name="Empathy"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Will"/>
    
    <skill rating="1" name="Athletics"/>
    <skill rating="1" name="Fight"/>
    <skill rating="1" name="Investigate"/>
    <skill rating="1" name="Rapport"/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/gus.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Gus</charname>
    <playername>Gus</playername>
    <description>
      A cat who tries to get food and territory while transformed.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Burglar While Shaping Into Other Cats</aspect>
    <aspect type="Trouble">Territory</aspect>
    <aspect type="Burdens">Everyone</aspect>
    <aspect type="True-Name">Moonlit Hunter</aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Shaping"/>
    
    <skill rating="3" name="Burglary"/>
    <skill rating="3" name="Naming"/>
    
    <skill rating="2" name="Investigate"/>
    <skill rating="2" name="Notice"/>
    <skill rating="2" name="Stealth"/>
    
    <skill rating="1" name="Lore"/>
    <skill rating="1" name="Deceive"/>
    <skill rating="1" name="Will"/>
    <skill rating="1" name="Territory"/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      +2 to use Shaping to transform into a non-cat.
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>

=== kbaird/Fate-XSLT/characters/Romance_in_the_Air/2nd_foundation.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/romance_in_the_air_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Foundation (Second)</charname>
    <playername>Romance in the Air Great Power</playername>
    <description>An adaptation from Isaac Asimov's Foundation Series</description>
  </id>
  <refresh free-stunts="1"/>
  <aspects>
    <aspect type="High-Concept">Hidden Cabal of Mentalics and Psychohistorians</aspect>
    <aspect type="Color">We'll Change Your Mind Before You Know We've Gone</aspect>
    <aspect type="Internal&#160;Trouble">Squabbling at the table and Underestimating Others</aspect>
  </aspects>
  <skills shape="flat">
    <skill rating="4" name="Diplomacy"/>
    <skill rating="5" name="Espionage"/>
    <skill rating="2" name="Industry"/>
    <skill rating="3" name="Warfare"/>
  </skills>
  <stunts>
    <stunt name="The Seldon Plan Must Continue">
      By Degrading Espionage by 2 ranks, automatically Create the misleading Advantage
      "Utterly Destroyed" on the Second Foundation with 2 Free Invocations.
    </stunt>
    <stunt name="Janissaries">
      Because you command a secretive martial order of infiltrators,
      you can attack with Espionage to inflict military stress. When doing so,
      your Espionage degrades as if it were Warfare, and is restored the same
      way.
    </stunt>
  </stunts>
</character>
