=== kbaird/Fate-XSLT/characters/FateCore/fcs.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, current-fate-points, aspects, skills, extras, stunts, consequences?, hacks?, phase-trio, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
    <!ELEMENT current-fate-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (High-Concept|Trouble) #IMPLIED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra name CDATA #REQUIRED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ELEMENT function (#PCDATA)>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions  (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption  (true|false) "false"> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks skill-modes (true|false) "false"> <!-- Fate System Toolkit     -->

    <!ELEMENT phase-trio (phase*)>
      <!ELEMENT phase (events*)>
        <!ATTLIST phase num   CDATA #REQUIRED>
        <!ATTLIST phase title CDATA #IMPLIED>
        <!ELEMENT events (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/FateCore/martin_liu.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE fate-core SYSTEM "fcs.dtd">
<character>
  <id>
    <charname>Martin Imiritish ke'Tolosa Liú</charname>
    <playername>Kevin C. Baird</playername>
    <description>
    Slightly below-average sized Elf of Han Chinese ancestry (186 cm, 70 Kg). Medium-length black hair.
    Often wears glasses as a Google Glass-style HMD for commlink (as many people do).
    Typically dresses a bit more formally than is standard for Tarislar.
  </description>
  </id>
  <refresh>3</refresh>
  <current-fate-points>3</current-fate-points>
  <aspects>
    <aspect type="High-Concept">Elven 巫人 expatriate from PDX</aspect>
    <aspect type="Trouble">Find a Clever Way to Minimize Harm</aspect>
    <aspect phase-num="1">Chinese Diaspora</aspect>
    <aspect phase-num="2">SINner citizen (&amp; Border Patrol veteran) of Tír Tairngire</aspect>
    <aspect phase-num="3">My Country Should Liberalize While Remaining the Elven Homeland</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Magic"/>
    <skill rating="3" name="Rapport"/>
    <skill rating="3" name="Will"/>
    <skill rating="2" name="Contacts"/>
    <skill rating="2" name="Lore"/>
    <skill rating="2" name="Physique"/>
    <skill rating="1" name="Athletics"/>
    <skill rating="1" name="Resources"/>
    <skill rating="1" name="Empathy"/>
    <skill rating="1" name="Notice"/>
  </skills>
  <extras>
    <extra>Magician: 巫人 (wū rén) in the 五行 (wŭ xíng) tradition</extra>
    <gadget name="Talisman">
      <function>Power Focus</function>
      <flaws>
        <flaw>Geas: reduces Magical power when absent</flaw>
        <flaw>Suggests 五行 Tradition</flaw>
      </flaws>
      <aspects>
        <aspect>Ox bone 麻将 (májiăng) tile bracelet</aspect>
      </aspects>
      <benefits>
        <benefit name="Summoning Aid">
          +2 to Create an Advantage with Magic when initially summoning a Spirit
        </benefit>
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="Spellcaster">
      Can use Magic skill with logical justification &amp; limitations for described spell.
      See notes.
    </stunt>
    <stunt name="Spirit Summoner">
      Can use Magic skill with logical justification &amp; limitations for described spirit.
      See notes.
    </stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1" title="Childhood">
      <events>
    2035: Tír Tairngire secedes from SSC; CFS kicked out of UCAS
    2036: TT invades northern CFS to Redding
    2041-2044: Nationalist War in China
    2042: Liu's parents emigrate from Beijing to TT
    2046-05-08 17:15:12 -0700: Liu born in Cara'Sir (Portland), TT
    Both parents are 1st Generation Han Chinese Elves who emigrated from
    greater Beijing to Tír Tairngire, motivated by the welcoming-to-metahumans
    rhetoric of TT's founding and the unrest in China at that time.

    Under Tír Tairngire's autocratic government, Martin was a member of the
    Rinelle ke'Tesrae's moderate/liberal wing, favoring democratic elections
    and a reduction/elimination of the formal caste system. Since the elections
    of 2065, he eschews revolutionary action in favor of "within the system"
    reforms. He has no particular admiration for the previous unelected
    Princes, and adheres to no significant racism directed at either metatypes
    or ethnic backgrounds, thereby opposing the Elf supremacist factions in the
    Rinelle [LOP7-8/SofNA142-3]. His family spoke mainly 普通话 at home. His
    true native language is now Sperethiel, and he has a strong non-native
    command of English.
   </events>
    </phase>
    <phase num="2" title="Early Adulthood">
      <events>
    2064: Liu undergoes Rite of Passage [TT57]. For the Bridging portion, he
    went to Anthony Lakes, Whitman National Forest in Northeastern Tír
    Tairngire. Tír Tairngirenes can be issued their standard Peace Force
    survival knife before deferred military service so they can use it in the
    Bridging, as Liu did. For the Naming portion, he chose to replace his birth
    name Resperentish with Imiritish ke'Tolosa, and made appropriate democratic
    reforms to the usual declarations of loyalty, cf. Reconstructionist Judaic
    bar mitzvah.
    2065: 1st open TT elections, Larry Zincan elected High Prince. Liu voted for him.
    2067: PCC absorbs Ute nation w/much Ute unrest
    2068: Martin gets B.A. in Applied Thaumaturgy from UTT in Serentaneyo
    (Eugene), starts mandatory 2-year military service in Border Patrol. Liu
    served as a Lt. in the Border Patrol due to his parents being Chivalry rank
    [TT59].
   </events>
    </phase>
    <phase num="3" title="The Near-Present">
      <events>
    2070: 2nd open TT elections, Zincan re-elected. Liu votes for him as High
    Prince again. Of the other Princes, he has spoken most approvingly of Jake
    Foster &amp; Amy Joubert [LOP14], with some support as well for Conall
    Taylor [LOP15]. 4th Rite of Progression held, Liu does not participate due
    to extended wilderness/border assignments for his military service, which
    he completes later that year.
    
    2072: M.A. in Applied Thaumaturgy from UTT in Serentaneyo (Eugene); Liu
    moves to Tarislar, Puyallup [Seattle126]. Lives a Low lifestyle near the
    hospital Deireadh an Tuartheil, "The End of the Song of the People/Tribe"
    [Seattle128, SS:HSLL12-13], where he volunteers with Health spells.
   </events>
    </phase>
  </phase-trio>
  <notes>






    Spellcaster notes:
    Keep it loose. Just do the Four Actions via the new Magic Skill, and give narrative
    description according to the particular Shadowrun spell desired. I figure a pretty loose
    definition of the stunt is OK, since it requires a completely new skill (Magic), burns a
    Stunt in addition to the required Magician extra, AND requires in-game narrative
    justification from the player.

    The particulars of each spell will be largely up to the caster. Some specific patterns
    (such as Attacks via mana spells being Opposed with Will; physical spells with Physique)
    will be fairly typical.

    Spirit Summoner notes:
    Can petition the Celestial Bureaucracy for magical favors. Again, keep it loose, and use
    the new Magic Skill. Maybe start with Creating the "Owes Service to [me]" Advantage on a
    specific Spirit that provides Active Opposition with its highest-rated Skill. Spending an
    action to Create more Advantages simply adds more invocations (i.e., services). The
    narrative particulars depend on the specific type of Spirit, etc.

    Drain:
    Use the options for Extra Effort and Extreme Effort from Fate System Toolkit, trading
    stress and/or consequences for bonuses.

    For even more detail, we could define the 五行 tradition as a character via the Fate Fractal.
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/kaerlen_fate_core.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE fate-core SYSTEM "fcs.dtd">
<character>
  <id>
    <charname>Kaerlen Santor d'Sivis</charname>
    <playername>Kevin C. Baird</playername>
    <description>
    A Gnome as dispassionate as Lorne Michaels with a blond ponytail &amp; close-cropped goattee.
    3'7", 47lbs. 60 years old. Usually impeccably dressed in high-falutin' Clebdecher Glamerweave (Sharn55).
  </description>
  </id>
  <refresh>3</refresh>
  <current-fate-points>3</current-fate-points>
  <aspects>
    <aspect type="High-Concept">Speaker's Guild Lawyer</aspect>
    <aspect type="Trouble">Keep [Jenn's PC] Out Of Trouble</aspect>
    <aspect phase-num="1">Cozy up to the Goblinoids</aspect>
    <aspect phase-num="2">Foreign Advisor Enjoys the Company of Talenta Ladies</aspect>
    <aspect phase-num="3">Amoral Sharn Shyster</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Rapport"/>
    <skill rating="3" name="Deceive"/>
    <skill rating="3" name="Resources"/>
    <skill rating="2" name="Shoot"/>
    <skill rating="2" name="Empathy"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="1" name="Lore"/>
    <skill rating="1" name="Contacts"/>
    <skill rating="1" name="Notice"/>
    <skill rating="1" name="Athletics"/>
  </skills>
  <extras/>
  <stunts>
    <stunt name="Groomed for Nobility (House Sivis)">
    +2 to Rapport when dealing with high society
  </stunt>
    <stunt name="Popular">
    Rapport in place of Contacts if well-liked. Prior justification or spend a Fate Point (see FateCore121).
  </stunt>
    <stunt name="Mishpocha">
    When a House Sivis message station is available, spend a Fate Point to use Resources in place of Contacts, Investigate, Lore or some other
    roll where long-distance assistance from someone higher-ranked in House Sivis could conceivably help. Requires some dramatically suitable delay.
  </stunt>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
981YK: Kaerlen moves to Sharn and starts working as a House Sivis barrister on the staff of Josilian
  Kan d'Tarlian (N Gnome Bard3/Expert3, Sharn53), frequently on behalf of the city's Goblinoids -
  House Sivis elders wanted to establish a presence in Darguun, and Kaerlen is groomed for the role.
  He lived in Highwater, Upper Dura (Sharn37/55), and Josilian's offices are in Clifftop, Upper Dura.
990YK: Kaerlen is sent to Rhukaan Draal, Darguun as planned. His official role is as a minor legal
  advisor to the Lhesh's court, but he also spies.
   </events>
    </phase>
    <phase num="2">
      <events>
995YK: Kaerlen is relocated to Gatherhold, Talenta. Overall, his duties are similar in Talenta to
  what they were in Darguun. While there, he enjoyed the company of a Talenta Hulrar named
  Cyrrinda Errim (N Female Halfling Ranger3) who taught him the Halfling language and whose
  first name means "Beautiful Defender" (Races of The Wild 60). The Hulrar tribe is the 2nd-strongest
  tribe and the strongest voice for Talenta unification beyond the limited confederation preferred by
  the dominant Abramams, and the dissolution favored by social Darwinist and traditionalist "Holy"
  Uldra Sindrekel.
996YK: The Last War ends with the Treaty of Thronehold (996-11-11).
   </events>
    </phase>
    <phase num="3">
      <events>
997YK: Kaerlen served as [Jenn's PC]'s lawyer in Sharn, defending her on murder charges. He was unable to
  obtain an acquital, but was able to get her deported rather than imprisoned or maimed. She was then
  sent back to her home in Freeport on the condition that Kaerlen take responsibility for delivering
  her successfully.
   </events>
    </phase>
  </phase-trio>
  <notes>
938YK: Born in Korranberg (938-11-06).
961YK: Boranel becomes King of Breland.
962YK: Zilargo formally aligns with Breland.
969YK: Soon-to-be Lhesh Haruuc leads the rebellion that forms Darguun.
978YK: Reaches 40, the age of majority for Gnomes.
981YK: Phase One, above.
994YK: Cyre destroyed, becomes the Mournland.
995YK: Phase Two, above.
997YK: Phase Three, above.

Kaerlen's name means "Good Ruby" (Races of Stone 49). He has a fondness for non-Gnomish women, especially
Talenta Halflings. Not that he's averse to Gnomish women or "tall ladies" at all. He has met few Dwarven
women.

Member of House Sivis (ECS236) and its Speaker's Guild (DrM73), employed as needed for the campaign
in public. Possibly working for House Sivis as an Agent (DrM14).

Sivis members in good standing can use a Message Station for free, and other services at 50% cost.
Sivis families are also prone to giving each other aid - not quite Favored in House, but helpful (DrM72).

Folks Kaerlen knows:
 1) Cyrrinda Errim (N Female Halfling Ranger3), ex-lover, very friendly.
  They might still be together if Kaerlen hadn't had to relocate.
 2) Dinagaera Owbaer, a Korranberg librarian (Female Gnome) - they hooked up a few times, friends.
 3) Corius Corralyn d'Sivis (LN Male Gnome Expert 6, DrM76)
 4) One or more Goblinoids in Sharn, perhaps former clients
 5) Josilian Kan d'Tarlian (Male Gnome, Sharn 53) - former employer in Sharn
 6) Solirion Torralyn d'Sivis (N Male Gnome, Sharn45) - head of the Speaker's Guild in Sharn
 7) Hellien Clamas Clebdecher (LN Female Gnome, Sharn55) - best Gnome tailoress in Highhold, Sharn
  Clebdecher Glamerweave (Sharn55/158) costs 500+ gp and grants a +2 to Diplomacy
 8) Thurik Davandi (LN Male Gnome, Sharn 66) - Upper Menthis city councilor in Sharn, tailor
 9) Some minor courtier(s) in Rhukaan Draal, Darguun
10) Some minor courtier(s) in Gatherhold, Talenta
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/FateCore/zird_the_arcane.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE fate-core SYSTEM "fcs.dtd">
<character>
  <id>
    <charname>Zird the Arcane</charname>
    <playername>sample FATE Core character</playername>
    <description>A sharp-featured scholar with a dark triangular beard.</description>
  </id>
  <refresh>2</refresh>
  <current-fate-points>2</current-fate-points>
  <aspects>
    <aspect type="High-Concept">Wizard for Hire</aspect>
    <aspect type="Trouble">Rivals in the Collegia Arcana</aspect>
    <aspect phase-num="1">If I Haven't Been There, I've Read About It</aspect>
    <aspect phase-num="2">Not The Face!</aspect>
    <aspect phase-num="3">Doesn't Suffer Fools Gladly</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Lore"/>
    <skill rating="3" name="Rapport"/>
    <skill rating="3" name="Crafts"/>
    <skill rating="2" name="Athletics"/>
    <skill rating="2" name="Will"/>
    <skill rating="2" name="Investigate"/>
    <skill rating="1" name="Fight"/>
    <skill rating="1" name="Resources"/>
    <skill rating="1" name="Contacts"/>
    <skill rating="1" name="Notice"/>
  </skills>
  <extras>
    <extra>Collegia Arcana Mage</extra>
  </extras>
  <stunts>
    <stunt name="Scholar, Healer">
    Can make Physical Recovery attempts w/Lore
  </stunt>
    <stunt name="Friendly Liar">
    Can use Rapport in place of Deceive to Create Advantages predicated on a lie.
  </stunt>
    <stunt name="The Power of Deduction">
    Once per scene you can spend a fate point (and a few minutes of observation) to make a
    special Investigate roll representing your potent deductive faculties. For each shift
    you make on this roll you discover or create an aspect, on either the scene or the target
    of your observations, though you may only invoke one of them for free.
  </stunt>
    <stunt name="I've Read About That!">
    You’ve read hundreds—if not thousands—of books on a wide variety of topics. You can spend
    a fate point to use Lore in place of any other skill for one roll or exchange, provided
    you can justify having read about the action you’re attempting.
  </stunt>
  </stunts>
  <consequences>
    <consequence severity="Mild">mild one</consequence>
  </consequences>
  <phase-trio>
    <phase num="1">
      <events>Some events</events>
    </phase>
    <phase num="2">
      <events>Some events</events>
    </phase>
    <phase num="3">
      <events>Some events</events>
    </phase>
  </phase-trio>
</character>
