=== kbaird/Fate-XSLT/characters/AetherSea/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, aspects, approaches, stunts, consequences?, notes?)>

  <!ELEMENT id (charname, playername, species, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT species (#PCDATA)> <!-- TODO: restrict to species list - requires XSD instead of DTD -->
    <!ELEMENT description (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh current CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (High-Concept|Trouble|Background|Ship|Free) "Free">

  <!ELEMENT approaches (approach*)>
    <!ELEMENT approach (#PCDATA)>
    <!ATTLIST approach name (Careful|Clever|Flashy|Forceful|Quick|Sneaky) #REQUIRED>
    <!ATTLIST approach rating CDATA #REQUIRED>

  <!ELEMENT stunts (magic?, stunt*)>
    <!ELEMENT magic (dabbles-in?, focuses-on?, permanent-magic?)>
      <!ELEMENT dabbles-in (#PCDATA)> <!-- TODO: restrict to school list, as focuses-on/@within - requires XSD instead of DTD -->
      <!ELEMENT focuses-on (#PCDATA)> <!-- requires a justifying Aspect -->
      <!ATTLIST focuses-on within (Alteration|Animation|Evocation) #REQUIRED>
      <!ELEMENT permanent-magic (#PCDATA)> <!-- requires a justifying Aspect -->
      <!ATTLIST permanent-magic name CDATA #REQUIRED>
    <!ELEMENT stunt (#PCDATA)>
    <!ATTLIST stunt name CDATA #REQUIRED>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

  <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Do_FotFT/curious_cat.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/do_fotft_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Curious Cat</charname>
    <playername>Morgan Baird</playername>
    <description>
      Red-haired girl, wearing clothing that looks like the coat of a leopard.
    </description>
  </id>
  <refresh free-stunts="2"/>
  <aspects>
    <aspect type="Avatar">Ooh... What's That?</aspect>
    <aspect type="Banner-Trouble">Easily Distracted</aspect>
    <aspect type="Dragon"></aspect>
    <aspect>I'll Find a Way In!</aspect>
    <aspect></aspect>
  </aspects>
  <approaches>
    <approach rating="2" name="Careful"/>
    <approach rating="3" name="Clever"/>
    <approach rating="0" name="Flashy"/>
    <approach rating="1" name="Forceful"/>
    <approach rating="1" name="Quick"/>
    <approach rating="2" name="Sneaky"/>
  </approaches>
  <stunts>
    <stunt name="Cheshire Catting">
      Because I am like the Cheshire Cat, I Sneakily Overcome at +2 when being invisible would help.
    </stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <notes>
    Wants to be good at escaping by being nimble &amp; cartwheeling in the air.
    Carries a spyglass.
    Comes from a cat-themed planet (Felinia?) where airships have cat decorations.
    They also have a festival called "Kitnip", and greet each other with high-fives.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/TheTwoGeorges/thomas_bushell.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fae_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateAccelerated/character.dtd">
<character>
  <id>
    <charname>Thomas Bushell ("Bush-ELL")</charname>
    <playername>http://turtledove.wikia.com/wiki/Thomas_Bushell</playername>
    <description>
      Thomas Bushell is a colonel in the Royal American Mounted Police and the
      chief of the RAM's Upper California section. In 1995, he is 48 years old
      and a compact, solidly made man of European descent, with brown hair and
      a mustache.

      In the 1970s, Bushell served as a Lieutenant in the Royal North American
      Army. He served with his fellow Lieutenant Horace Bragg and was assigned
      Staff Sgt. Samuel Stanley as his senior non-com on the border with Nueva
      Espa√±a. Several disputes arose during this period which resulted in
      border skirmishes. In one, Bushell was wounded attempting to rescue one
      of his men who was down. Both were saved by Stanley.

      Lived in the NAU capitol of Victoria for many years. Divorced wife Irene
      after catching her in bed with Sir David Clarke; Irene and David are now
      married. Bushell started drinking. Bragg (now Lt. General and commandant
      of the RAM) reassigned him to head the Upper California section in New
      Liverpool so he could get a fresh start.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Colonel in the Royal American Mounted Police</aspect>
    <aspect type="Trouble">The Bottle Helps Me Forget</aspect>
    <aspect>I Owe Sam Stanley My Life</aspect>
    <aspect>Majored in Classics</aspect>
    <aspect>&#160;</aspect>
  </aspects>
  <approaches>
    <approach rating="2" name="Careful"/>
    <approach rating="2" name="Clever"/>
    <approach rating="1" name="Flashy"/>
    <approach rating="3" name="Forceful"/>
    <approach rating="0" name="Quick"/>
    <approach rating="1" name="Sneaky"/>
  </approaches>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/Banished/the_children_of_xarrat.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fae_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateAccelerated/character.dtd">
<character>
  <id>
    <charname>The Children of Xarrat</charname>
    <description>
      AKA "The Children of the Forgiving God" or
      "The Followers of the Iron God of Eternal Mercy".

      Adherents dress in loose purple and white robes,
      with metal pentagons on necklaces.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">New Foreign Religion from the West</aspect>
    <aspect type="Trouble">Lovecraftian Secrets Behind a Smile</aspect>
    <aspect>Slowly Making Inroads From the Bottom Up</aspect>
    <aspect>We Scrupulously Keep Our Noses Clean</aspect>
    <aspect>We Have Genuine Occult Power</aspect>
  </aspects>
  <approaches>
    <approach rating="4" name="Careful"/>
    <approach rating="3" name="Clever"/>
    <approach rating="3" name="Flashy"/>
    <approach rating="2" name="Forceful"/>
    <approach rating="0" name="Quick"/>
    <approach rating="5" name="Sneaky"/>
  </approaches>
  <stunts>
    <stunt name="Charitable Works">
      +2 to Sneakily Create an Advantage representing
      a good reputation among the lower classes.
    </stunt>
    <stunt name="Paranoid: ☐">
      Once per session, when an entity takes action to either attack or
      investigate you, you may attempt to Carefully Overcome to become
      aware of the threat, even if doing so would normally stretch credibility.
    </stunt>
    <stunt name="Ritualist II: ☐">
      Once per session, when facing a Challenge, you may perform a magic ritual
      to automatically succeed with style at any one component task of the Challenge.
    </stunt>
  </stunts>
  <consequences/>
  <notes>
"Xarrat" is the Azerbaijani word for "carpenter".

Culty Goodness: Blood of the Masters (T:BS&amp;J, pg 170)
The **Shining Vampire Sect** kidnaps several masters
in order to drink their blood and steal their power

Probably more interesting of the Children of Xarrat aid the
PCs against the Shining Vampire Sect.

I should probably make a reverend of some sort.

Cf. Evil Cultists (T:BS&amp;J, pg 156)
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/Do_FotFT/subtle_parrot.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/do_fotft_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Subtle Parrot</charname>
    <playername>Morgan Baird</playername>
    <description>
      Wears multi-colored clothing, with metallic colors reminiscient of the good dragons in 1st Edition D&amp;D.
    </description>
  </id>
  <aspects>
    <aspect type="Avatar"></aspect>
    <aspect type="Trouble"></aspect>
    <aspect type="Dragon">[not yet]</aspect>
    <aspect></aspect>
    <aspect></aspect>
  </aspects>
  <approaches>
    <approach rating="" name="Careful"/>
    <approach rating="" name="Clever"/>
    <approach rating="" name="Flashy"/>
    <approach rating="" name="Forceful"/>
    <approach rating="" name="Quick"/>
    <approach rating="" name="Sneaky"/>
  </approaches>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    <consequence severity="Moderate">moderate one</consequence>
    <consequence severity="Severe">severe one</consequence>
    -->
  </consequences>
</character>
