=== kbaird/Fate-XSLT/characters/AetherSea/ship.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT ship (id, aspects?, approaches?, components?, stunts?, consequences?, notes?)>
  <!ATTLIST ship size (Shuttle|Working|Major|Ultramassive) #REQUIRED>

  <!ELEMENT id (name, description)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)> <!-- as many as there are crew members -->
    <!ATTLIST aspect type (High-Concept|Trouble|Background|Ship|Free) "Free">

  <!-- Also allow Skilled at / Bad at, cf. Royal Glory, pg 33 -->
  <!ELEMENT approaches (approach*)>
    <!ELEMENT approach (#PCDATA)>
    <!ATTLIST approach name (Careful|Clever|Flashy|Forceful|Quick|Sneaky) #REQUIRED>
    <!ATTLIST approach rating CDATA #REQUIRED>

  <!ELEMENT components (component*)>
    <!ELEMENT component (#PCDATA)>
    <!ATTLIST component name CDATA #REQUIRED>

  <!ELEMENT stunts (stunt*)>
    <!ELEMENT stunt (#PCDATA)>
    <!ATTLIST stunt name CDATA #REQUIRED>

  <!-- Resources Stress Track (pg26) -->
  <!-- Stations: Control, Communication, plus stunts (pg27) -->
  <!ELEMENT consequences (consequence*)>
    <!-- Extreme Consequences (pg29) -->
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe|Extreme) #REQUIRED>

  <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/AetherSea/mining_vessel_22.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/aether-sea-ship_html.xsl"?>
<!DOCTYPE ship SYSTEM "ship.dtd">
<ship size="Working">
  <!-- Refresh and Stunts derived from Size, pg 25
       Can be supplemented by PCs
    -->
  <id>
    <name>Deeprunner Flagship, Mining Vessel #22</name>
    <description>
      Like many Deeprunner vessels, #22 is made out of hewn stone.
      It resembles a cross between a ship and an ancient castle. And
      like a castle, itâ€™s meant to discourage attacks; the cargo bays
      might be full of gold or other precious minerals, after all, so
      appearing untouchable is advantageous.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Impenetrable Fortress in the Sea</aspect>
    <aspect type="Ship">When In Doubt, Smash It</aspect>
  </aspects>
  <components>
    <component name="Landing Struts">
      Can land planetside on its own.
    </component>
    <component name="Stone Armor">
      All stress dealt to this ship is reduced by 1.
    </component>
  </components>
  <!-- Resources stress track derived from Size, pg 26 -->
  <!-- Starts with 2 Stations, pg 27 -->
  <!-- Consequences, pg 29 -->
</ship>
