=== kbaird/Fate-XSLT/characters/ShotC/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, skills, languages?,
                     extras?, stunts, stress?, consequences?, hacks?, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
      <!ATTLIST refresh base        CDATA #IMPLIED>
      <!ATTLIST refresh current     CDATA #IMPLIED>
      <!ATTLIST refresh free-stunts CDATA #IMPLIED>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect gonzo (true|false) "false">
      <!ATTLIST aspect type  (High-Concept|Spirit|Trouble|Call-To-Action|War-Story|Team-Up) #REQUIRED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT skills (role*, skill*)>
    <!ATTLIST skills name CDATA "Skills">
      <!ELEMENT role (skill*)>
      <!ATTLIST role gonzo  (true|false) "false">
      <!ATTLIST role name   CDATA #REQUIRED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra name CDATA #IMPLIED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name          CDATA #REQUIRED>
      <!ATTLIST gadget notes         CDATA #IMPLIED>
      <!ATTLIST gadget override-name CDATA #IMPLIED>
        <!ELEMENT function (#PCDATA)>
          <!ELEMENT flaws (flaw*)>
            <!ELEMENT flaw (#PCDATA)>
          <!ELEMENT benefits (benefit*)>
            <!ELEMENT benefit (#PCDATA)>
            <!ATTLIST benefit cost CDATA #IMPLIED>
            <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt gonzo-level (0|1|2|3) "0"> <!-- default zero level means "non-gonzo" -->
      <!ATTLIST stunt name  CDATA #REQUIRED>

    <!ELEMENT stress (#PCDATA)>
      <!ATTLIST stress mental   (2|3|4) "3">
      <!ATTLIST stress physical (2|3|4) "3">

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks skill-roles (true|false) "true">

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/ShotC/cisco_ramon.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname nickname="Cisco">Francisco Ramon</charname>
    <playername>Proto-NPC</playername>
    <description>Kind of looks like Carlos Valdes</description>
  </id>
  <aspects>
    <aspect type="High-Concept">Awkward Nerd With a Lot of Potential</aspect>
    <aspect type="Trouble">Doesn't Put His Best Foot Forward</aspect>
    <aspect type="Call-To-Action">Particle Accelerator Explosion</aspect>
    <aspect type="War-Story">&#160;</aspect>
    <aspect gonzo="true" type="Team-Up">Team Flash's Vibe</aspect>
  </aspects>
  <skills>
    <role name="The&#160;Brain"> <!-- ShotC pg39 -->
      <skill name="Computers" add="0"/>
      <skill name="Gadgetry"  add="0"/>
      <skill name="Insight"   add="1"/>
      <skill name="Knowledge" add="0"/>
    </role>
    <role name="The&#160;Inventor"> <!-- ShotC pg40 -->
      <skill name="Awareness" add="2"/>
      <skill name="Contacts"  add="0"/>
      <skill name="Insight"   add="0"/>
      <skill name="Persuade"  add="0"/>
    </role>
    <role gonzo="true" name="Vibe"> <!-- ShotC pg42 -->
      <skill name="Contacts"  add="0"/>
      <skill name="Insight"   add="0"/>
      <skill name="Persuade"  add="0"/>
      <skill name="Provoke"   add="2"/>
    </role>
    <skill name="Shoot" add="3"/>
  </skills>
  <stunts>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <stress mental="4" physical="2"/>
  <consequences/>
  <hacks skill-roles="true"/>
  <notes>
 </notes>
</character>
