=== kbaird/Fate-XSLT/characters/AtomicRobo/atomic-robo.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills, stress?, stunts, consequences?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation, description?)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (Concept|Mode|Omega) #REQUIRED>
      <!ATTLIST aspect mode-name CDATA           #IMPLIED>
      <!ATTLIST aspect signature (true|false)    #IMPLIED>

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ATTLIST mode stress-type (mental|physical|split) #IMPLIED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill rating CDATA #IMPLIED>
        <!ATTLIST skill add    CDATA #IMPLIED>
        <!ATTLIST skill cost   CDATA #IMPLIED> <!-- For Weird calculations -->

    <!ELEMENT stunts (stunt*, gadget*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name     CDATA    #IMPLIED>
      <!ELEMENT gadget (benefits*)>
      <!ATTLIST gadget name     CDATA    #IMPLIED>
      <!ATTLIST gadget function CDATA    #IMPLIED>
      <!ATTLIST gadget flaw     CDATA    #IMPLIED>
      <!ELEMENT benefits (benefit*)>
        <!ELEMENT benefit (#PCDATA)>
        <!ATTLIST benefit cost CDATA    #IMPLIED>
        <!ATTLIST benefit name CDATA    #IMPLIED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT experiences (experience*)>
      <!ELEMENT experience (#PCDATA)>
      <!ATTLIST experience used (true|false) #IMPLIED>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TesladyneSF-Scenarios/01Buzz/mcmansion_hive.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>McMansion / Hive</charname>
  <playername>NPC</playername>
  <affiliation>Buzz About the New Cell Tower</affiliation>
  <description>
    2659 Torrey Pines Drive, Brentwood, CA -
    Consider Swarms from Day After Ragnarok, pg 91 instead of this level of detail
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Relentless Cloud of Stings</aspect>
  <aspect type="Mode" mode-name="Hive">We're EVERYWHERE</aspect>
  <aspect type="Mode" mode-name="Beast">Eusocial Coordination</aspect>
  <aspect type="Mode" mode-name="Mutant">Defend the Queen</aspect>
  <aspect type="Omega">Not Scared of Bees? You Are Now.</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Hive" stress-type="physical">
   <skill name="Athletics"        cost="2"/>
   <skill name="Notice"           cost="1"/>
   <skill name="Physique"         cost="1"/>
   <skill name="Tooth &amp; Claw" cost="1"/> <!-- ARRPG pg87 -->
  </mode>
  <mode rating="2" name="Beast" stress-type="physical"> <!-- ARRPG pg87 -->
   <skill name="Athletics"        cost="2"/>
   <skill name="Notice"           cost="1"/>
   <skill name="Physique"         cost="1"/>
   <skill name="Provoke"          cost="1"/>
   <skill name="Tooth &amp; Claw" cost="1" add="1"/> <!-- ARRPG pg87 --> <!-- Beast Improvement -->
   <!-- Also Specialize 1 Trained Skill -->
  </mode>
  <mode rating="1" name="Mutant">
   <!-- easiest to just represent improvement as native skills here -->
   <skill name="Athletics" cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Physique"  cost="1"/>
   <skill name="Tooth &amp; Claw" cost="1"/> <!-- ARRPG pg87 -->
  </mode>
 </skills>
 <stunts>
  <stunt name="Flyer">
   Use Athletics to fly; ignore all ground-based obstacles when you do.
  </stunt>
  <stunt name="Grow the Hive">
   If a human (enough) character is Taken Out by stings, he/she gains (or replaces) a Severe Consequence of
   "Mutating into a Human/Bee Hybrid" that needs to be dealt with narratively (and quickly) before it can be
   recovered from. At a cost: weak against whatever the PCs brainstorm that makes sense.
  </stunt>
  <stunt name="Hard to Kill a Swarm of Bees">
   For any attack or advantage to have much effect, it must make sense for it to affect a swarm of bees.
  </stunt>
  <stunt name="Healing Factor">
   Once per scene, spend a fate point to reduce one of your consequences by one degree of severity
   (severe to major, major to mild, mild to nothing).
  </stunt>
  <stunt name="Lightning Reflexes">
   In a physical conflict, you always act first. If someone else in the conflict has a stunt that gives
   them the same ability, make an Athletics roll to see who goes first.
  </stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
Tooth and Claw is at ARRPG pg87
<!--
Modes with Athletics or Physique can give your character additional physical stress boxes, while modes with Provoke or Will can give
your character additional mental stress boxes. A mode with one or more of these skills rated at Fair (+2) adds one box, while one
rated at Good (+3) adds two boxes.

If a mode has skills that apply to both types, the bonus boxes can apply to either one. For example, the Action mode has Athletics,
Physique, and Provoke. If you've given it a rating of Good (+3), you could have two more physical stress boxes, two more mental stress
boxes, or one in each.

Bonus stress boxes from your Good (+3) and Fair (+2) modes are cumulative. So if you have Good (+3) Action and Fair (+2) Intrigue, both
of which have the Athletics skill, you can get three more physical stress boxesâ€”two from Action and one from Intrigue.
-->
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneSF/dennis_kim.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Dennis Kim</charname>
  <playername>Supporting NPC</playername>
  <affiliation>Tesladyne SF (Resident Scientist NPC)</affiliation>
  <description>
    22-year old, scruffy, Phish T-shirt, acoustic guitar
    http://bigbangtheory.wikia.com/wiki/Dennis_Kim
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Brilliant Stoner Resident Scientist</aspect>
  <aspect type="Mode" mode-name="Science">Literally Plays 11-Dimensional Chess</aspect>
  <aspect type="Mode" mode-name="Banter">Abrasive Boy Genius Who Mellowed Out (Mostly)</aspect>
  <aspect type="Mode" mode-name="Intrigue">Smuggled My Grandfather Out of North Korea</aspect>
  <aspect type="Omega">Youngest Recipient of the Stevenson Award</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science" stress-type="mental">
   <skill name="Higher-Dimensional Math" add="2"/>
   <skill name="Notice"                  cost="1"/>
   <skill name="Pharmacology"            add="0"/>
   <skill name="Theoretical Physics"     add="2"/>
   <skill name="Will"                    cost="1"/>
   <skill name="(all other Sciences)"    cost="1"/>
  </mode>
  <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
   <skill name="Contacts" cost="1"/>
   <skill name="Deceive"  cost="2"/>
   <skill name="Empathy"  cost="3"/>
   <skill name="Notice"   cost="1"/>
   <skill name="Provoke"  cost="1" add="1"/>
   <skill name="Rapport"  cost="1"/>
   <skill name="Will"     cost="1"/>
  </mode>
  <mode rating="1" name="Intrigue"> <!-- ARRPG pg84 -->
   <skill name="Athletics" cost="2"/>
   <skill name="Burglary"  cost="1"/>
   <skill name="Contacts"  cost="1"/>
   <skill name="Deceive"   cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Stealth"   cost="2"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Well-Earned Arrogance">
   +2 to Attack with Provoke when belittling or insulting the target [ARRPG269]
  </stunt>
  <stunt name="String Theory is a Dead End">
   +2 to Create an Advantage with Theoretical Physics when critiquing another's work
  </stunt>
  <stunt name="Wunderkind">
   +2 when using Theoretical Physics during a Brainstorm
  </stunt>
  <stunt name="Dime Bag">
   +2 to Create an Advantage with Contacts among stoners
  </stunt>
  <stunt name=" ">TBD</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneSF/frank_rogers.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Frank Rogers</charname>
  <playername>Michael Wood</playername>
  <affiliation>Tesladyne SF (Action Scientist PC)</affiliation>
  <description>
    TBD
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">TBD</aspect>
  <aspect type="Mode" mode-name="Telepath">TBD</aspect>
  <aspect type="Mode" mode-name="Martial&#160;Artist">TBD</aspect>
  <aspect type="Mode" mode-name="Human&#160;Resources">
   The Batman of Human Resources
  </aspect>
  <aspect type="Omega">TBD</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Telepath" stress-type="mental"> <!-- ARRPG pg92 -->
   <skill name="Deceive"        cost="2"/>
   <skill name="Empathy"        cost="3"/>
   <skill name="Hallucinations" cost="2"/>
   <!-- OR Focus 1 Trained Skill instead of Hallucinations -->
   <skill name="Provoke"        cost="1"/>
   <skill name="Rapport"        cost="1"/>
   <skill name="Will"           cost="1"/>
  </mode>
  <mode rating="2" name="Martial&#160;Artist" stress-type="physical"> <!-- ARRPG pg88 -->
   <skill name="Athletics" cost="2"/>
   <skill name="Combat"    cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Physique"  cost="1"/>
   <skill name="Stealth"   cost="2"/>
   <skill name="Will"      cost="1"/>
  </mode>
  <mode rating="1" name="Human&#160;Resources">
   <skill name="Contacts"  cost="1"/>
   <skill name="Deceive"   cost="2"/>
   <skill name="Empathy"   cost="3"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Rapport"   cost="2"/>
   <skill name="Will"      cost="1"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Biofeedback">
   You are capable of using your psionic powers to enhance your physical
   capabilities for a short time. You must make an Overcome roll to enter the
   proper trance state for this power, and anyone who can reasonably disrupt
   your concentration may oppose you. (Alternately, you may take a Mild
   Consequence to automatically succeed.)
   If you succeed, you may raise Athletics OR Physique by +2 for the remainder
   of the scene, with all the benefits of doing so (which could mean more
   stress boxes and whatnot). If you succeed with style, you may raise BOTH.
   --DAR33
  </stunt>
  <stunt name="Borrowed Knowledge">
   Pick another character (PC or NPC) who's in the scene with you. You can use
   one of their skills for one roll in this scene, whether it's a skill you
   already have or not. When you do this, pay that character a fate point.
  </stunt>
  <stunt name="Iron Robe Technique">
   Armor: 2
  </stunt>
  <stunt name="Lightning Reflexes">
   In a physical conflict, you always act first. If someone else in the
   conflict has a stunt that gives them the same ability, make an Athletics
   roll to see who goes first.
  </stunt>
  <stunt name="Mind Reader">
   When you use Empathy to create an advantage by discovering another
   character's aspects, you don't need to speak with them and it takes
   virtually no time.
  </stunt>
  <stunt name="One With Everything">
   Use Will to create an advantage through meditation or
   focus when you have a moment to breathe and concentrate.
  </stunt>
  <stunt name="Remote Viewing">
   Pick a character you’ve met (PC or NPC), whether or not they’re in the scene
   with you. You can briefly perceive using their senses instead of your own.
   The clarity of your perception will depend on the distance involved and how
   well you know the other character. For example, if you’re seeing through the
   eyes of your brother in the next room, it’ll be crystal clear. If you’re
   seeing through the eyes of a Majestic 12 guard several miles away with whom
   you spoke a few days ago, it’ll be blurry and unreliable.
  </stunt>
  <stunt name="Versatile Will">
   Switch ANY skill with Will once per scene
  </stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland-Scenarios/01Buzz/human_bee_hybrid.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Mutant Human/Bee Hybrid</charname>
  <playername>NPC</playername>
  <affiliation>Buzz About the New Cell Tower</affiliation>
  <description>
    Whatever image haunts your dreams after reading about Shadowrun's Insect Spirits.
  </description>
 </id>
 <current-fate-points>4</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Human/Bee Hybrid</aspect>
  <aspect type="Mode" mode-name="Beast">Queen of the Hive</aspect>
  <aspect type="Mode" mode-name="Banter">Destined to Replace Humanity</aspect>
  <aspect type="Mode" mode-name="Mutant">Hybrid Vigor</aspect>
  <aspect type="Omega">&#160;</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Beast" stress-type="physical"> <!-- ARRPG pg87 -->
   <skill name="Athletics"        cost="2"/>
   <skill name="Notice"           cost="1"/>
   <skill name="Physique"         cost="1"/>
   <skill name="Provoke"                   add="1"/> <!-- Mutant mods -->
   <skill name="Tooth &amp; Claw" cost="1" add="2"/> <!-- ARRPG pg87, Mutant mods -->
   <!-- Also Specialize 1 Trained Skill -->
  </mode>
  <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
   <skill name="Contacts" cost="1"/>
   <skill name="Deceive"  cost="2"/>
   <skill name="Empathy"  cost="3" add="1"/> <!-- Mutant mods -->
   <skill name="Notice"   cost="1"/>
   <skill name="Provoke"  cost="1"/>
   <skill name="Rapport"  cost="1"/>
   <skill name="Will"     cost="1" add="2"/> <!-- Mutant mods -->
  </mode>
  <mode rating="1" name="Mutant"> <!-- ARRPG pg88 -->
   <!--
        Specialize 2 Trained Skills
        Specialize 1 Focused Skill
        Focus      1 Trained Skill
   -->
  </mode>
 </skills>
 <stunts>
  <stunt name="Healing Factor">
   Once per scene, spend a fate point to reduce one of your consequences by one degree of severity
   (severe to major, major to mild, mild to nothing).
  </stunt>
  <stunt name="Unnerving Presence">
   +2 to Create an Advantage with Provoke when you rely on fear or awe.
  </stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
  <!--
  Mutant Mode Improvements
  X Specialize two trained skills: [Tooth and Claw, Will].
  X Specialize one focused skill: [Provoke].
  X Focus one trained skill: [Empathy].
  -->
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/barry_allen-police_scientist.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
  <id>
    <charname nickname="The Flash">Barry Allen</charname>
    <playername>Proto-NPC</playername>
    <affiliation>Central City Police Department</affiliation>
    <description>Kind of looks like Grant Gustin</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Affable Straight-Laced Nerd</aspect>
    <aspect type="Mode" mode-name="Police&#160;Scientist">Quick Connections</aspect>
    <aspect type="Mode" mode-name="Action">Tireless</aspect>
    <aspect type="Mode" mode-name="Metahuman">The Fastest Man Alive</aspect>
    <aspect type="Omega">Obsessed with Father's Innocence and Iris</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Police&#160;Scientist" stress-type="mental">
      <skill name="Athletics" cost="2" add="1"/>
      <skill name="Chemistry" cost="0"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Empathy"   cost="3"/>
      <skill name="Forensics" cost="0" add="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physics"   cost="0"/>
      <skill name="Will"      cost="1" add="1"/>
    </mode>
    <mode rating="2" name="Action" stress-type="physical"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="1" name="Metahuman"> <!-- Reskin of Mutant, ARRPG pg88 -->
     <!--
          Specialize 2 Trained Skills: Forensics, ?
          Specialize 1 Focused Skill:  Athletics
          Focus      1 Trained Skill:  Will
     -->
    </mode>
  </skills>
  <stunts>
    <stunt name="Healing Factor">
      Once per scene, spend a fate point to reduce one of your consequences by one
      degree of severity (severe to major, major to mild, mild to nothing).
    </stunt>
    <stunt name="Super-Speed">
      Absolutely faster than any human, but at a cost (typically underestimating danger due to overconfidence).
    </stunt>
    <stunt name="The Streak">
      +2 to Overcome with Athletics when moving at Super-Speed.
    </stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
    Metahuman/Mutant Mode Improvements:
      Specialize 2 Trained Skills: Forensics, ?
      Specialize 1 Focused Skill:  Athletics
      Focus      1 Trained Skill:  Will
 </notes>
</character>
