=== kbaird/Fate-XSLT/characters/AtomicRobo/atomic-robo.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills, stress?, stunts, consequences?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation, description?)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (Concept|Mode|Omega) #REQUIRED>
      <!ATTLIST aspect mode-name CDATA           #IMPLIED>
      <!ATTLIST aspect signature (true|false)    #IMPLIED>

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ATTLIST mode stress-type (mental|physical|split) #IMPLIED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill rating CDATA #IMPLIED>
        <!ATTLIST skill add    CDATA #IMPLIED>
        <!ATTLIST skill cost   CDATA #IMPLIED> <!-- For Weird calculations -->

    <!ELEMENT stunts (stunt*, gadget*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name     CDATA    #IMPLIED>
      <!ELEMENT gadget (benefits*)>
      <!ATTLIST gadget name     CDATA    #IMPLIED>
      <!ATTLIST gadget function CDATA    #IMPLIED>
      <!ATTLIST gadget flaw     CDATA    #IMPLIED>
      <!ELEMENT benefits (benefit*)>
        <!ELEMENT benefit (#PCDATA)>
        <!ATTLIST benefit cost CDATA    #IMPLIED>
        <!ATTLIST benefit name CDATA    #IMPLIED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT experiences (experience*)>
      <!ELEMENT experience (#PCDATA)>
      <!ATTLIST experience used (true|false) #IMPLIED>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TesladyneSF-NPCs/melissa_daskalakis.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Melissa Daskalakis (Μελισσα Δασκαλακισ)</charname>
  <playername>AR:RPG NPC</playername>
  <affiliation>CA Governor's Office liaison to Tesladyne's SF office</affiliation>
  <description>
   An amiable, athletic, well-dressed woman of Greek descent.
   Decorates her office with traditional Greek bull statues, as well as complex
   abstract art, like mazes, Celtic knots, Sini script, and Islamic calligraphy.
  </description>
 </id>
 <current-fate-points>5</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Minoan Palatine (GURPS AT104)</aspect>
  <aspect type="Mode" mode-name="Telepath">Psionics Are Beyond Good &amp; Evil</aspect>
  <aspect type="Mode" mode-name="Intrigue">Trust Me, I’m Looking Out For Your Best Interests</aspect>
  <aspect type="Mode" mode-name="Secret&#160;Agent">Help Tesladyne, It Will Become Useful To Us</aspect>
  <aspect type="Omega">I’m Not The Bad Guy Here</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Telepath" stress-type="mental"> <!-- ARRPG pg92 -->
   <skill name="Deceive"        cost="2"/>
   <skill name="Empathy"        cost="3"/>
   <skill name="Hallucinations" cost="2"/>
   <skill name="Provoke"        cost="1"/>
   <skill name="Rapport"        cost="1"/>
   <skill name="Will"           cost="1"/>
  </mode>
  <mode rating="2" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
   <skill name="Athletics" cost="2"/>
   <skill name="Burglary"  cost="1"/>
   <skill name="Contacts"  cost="1"/>
   <skill name="Deceive"   cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Stealth"   cost="2"/>
  </mode>
  <mode rating="1" name="Secret&#160;Agent"> <!-- ARRPG pg91 -->
   <skill name="Burglary" cost="1"/>
   <skill name="Contacts" cost="1"/>
   <skill name="Deceive"  cost="2"/>
   <skill name="Notice"   cost="1"/>
   <skill name="Stealth"  cost="2"/>
   <skill name="Vehicles" cost="2"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Borrowed Knowledge">
   Pick another character (PC or NPC) who’s in the scene with you. You can use
   one of their skills for one roll in this scene, whether it’s a skill you
   already have or not. When you do this, pay that character a fate point.
  </stunt>
  <stunt name="Cutting Words">
   When you invoke one of a target’s aspects as part of creating an advantage
   with Provoke, spend a fate point to also deal them a mental hit equal to the
   number of shifts you obtain on the roll.
  </stunt>
  <stunt name="Deep Tesladyne Cover">
   When operating undercover, you can use Deceive in place of Provoke or
   Rapport, as long as you’re acting “in character.”
  </stunt>
  <stunt name="Mind Reader">
   When you use Empathy to create an advantage by discovering another character’s
   aspects, you don’t need to speak with them and it takes virtually no time.
  </stunt>
  <stunt name="Versatile Deceive">
   Switch ANY skill with Deceive once per scene
  </stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland-NPCs/legion.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Legion</charname>
  <playername>Supporting NPC</playername>
  <affiliation>&#160;</affiliation>
  <description>&#160;</description>
 </id>
 <current-fate-points>0</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
   <aspect type="Concept">
     Braintape in Multiple Mechanical Insectoid Bodies
   </aspect>
   <aspect type="Mode" mode-name="Combat&#160;Stealthbot">
     Wall-Crawling Infiltrator
   </aspect>
   <aspect type="Mode" mode-name="Science">
     Broad But Shallow Generalist
   </aspect>
   <aspect type="Mode" mode-name="Thief">
     &#160;
   </aspect>
   <aspect type="Omega">
     &#160;
   </aspect>
 </aspects>
 <skills>
   <mode rating="3" name="Combat&#160;Stealthbot" stress-type="split">
   <skill name="Athletics" cost="2"/>
   <skill name="Burglary"  cost="1"/>
   <skill name="Combat"    cost="2"/>
   <skill name="Physique"  cost="1"/>
   <skill name="Stealth"   cost="2"/>
   <skill name="Will"      cost="1"/>
  </mode>
  <mode rating="2" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
   <skill name="Notice"               cost="1"/>
   <skill name="Will"                 cost="1"/>
   <skill name="(all other Sciences)" cost="1"/>
  </mode>
  <!--
       Specialize one trained skill.
       Focus one trained skill.
       Specialize one focused skill.
  -->
  <mode rating="1" name="Thief" stress-type="physical"> <!-- ARRPG pg288 -->
   <skill name="Athletics" cost="2"/>
   <skill name="Burglary"  cost="1"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Stealth"   cost="2"/>
   <!-- 4 pts of Improvements -->
  </mode>
 </skills>
 <stunts>
  <stunt name=" ">&#160;</stunt>
  <stunt name=" ">&#160;</stunt>
  <stunt name=" ">&#160;</stunt>
  <stunt name=" ">&#160;</stunt>
  <stunt name=" ">&#160;</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
   4 pts of Improvements from Thief mode
   If one of your modes is Science, also apply ALL of the following improvements:
  * Specialize one trained skill.
  * Focus one trained skill.
  * Specialize one focused skill.
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/nikola_tesla.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "atomic-robo.dtd">
<character>
  <id>
    <charname>Nikola Tesla</charname>
    <playername>sample Atomic Robo character</playername>
    <affiliation>Westinghouse Electric</affiliation>
  </id>
  <current-fate-points>5</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Eccentric Inventor of Beautiful Apparatuses</aspect>
    <aspect type="Mode" mode-name="Science" signature="true">Master of Lightning</aspect>
    <aspect type="Mode" mode-name="Banter">Magnetic Charm</aspect>
    <aspect type="Mode" mode-name="Action"/>
    <aspect type="Omega">My Method Is Different</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental">
      <skill name="Electrical Engineering" add="2"/>
      <skill name="Mechanical Engineering" add="2"/>
      <skill name="Physics" add="2"/>
      <skill name="Will" add="1"/>
      <skill name="Notice" add="1"/>
      <skill name="(All other Sciences)"/>
    </mode>
    <mode rating="2" name="Banter" stress-type="mental">
      <skill name="Contacts" add="1"/>
      <skill name="Deceit"/>
      <skill name="Empathy"/>
      <skill name="Provoke" add="1"/>
      <skill name="Rapport"/>
      <skill name="Will"/>
    </mode>
    <mode rating="1" name="Action">
      <skill name="Athletics" add="2"/>
      <skill name="Combat" add="1"/>
      <skill name="Physique"/>
      <skill name="Vehicles"/>
    </mode>
  </skills>
  <stunts/>
  <consequences>
    <consequence severity="Mild">mild one</consequence>
  </consequences>
  <experiences>
    <experience>experience1: this is longer than the others</experience>
    <experience>experience2</experience>
    <experience used="true">experience3</experience>
  </experiences>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/frank_rogers-bullshit.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Frank Rogers</charname>
  <playername>Michael Wood</playername>
  <affiliation>Tesladyne Oakland (Action Scientist PC)</affiliation>
  <description>
    TBD
  </description>
 </id>
 <current-fate-points>1</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">TBD</aspect>
  <aspect type="Mode" mode-name="Banter">TBD</aspect>
  <aspect type="Mode" mode-name="Martial&#160;Artist">TBD</aspect>
  <aspect type="Mode" mode-name="Human&#160;Resources">
   The Batman of Human Resources
  </aspect>
  <aspect type="Omega">TBD</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
   <skill name="Contacts" cost="1"/>
   <skill name="Deceive"  cost="2"/>
   <skill name="Empathy"  cost="3"/>
   <skill name="Notice"   cost="1"/>
   <skill name="Provoke"  cost="1"/>
   <skill name="Rapport"  cost="1"/>
   <skill name="Will"     cost="1"/>
  </mode>
  <mode rating="2" name="Martial&#160;Artist" stress-type="physical"> <!-- ARRPG pg88 -->
   <skill name="Athletics" cost="2"/>
   <skill name="Combat"    cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Physique"  cost="1"/>
   <skill name="Stealth"   cost="2"/>
   <skill name="Will"      cost="1"/>
  </mode>
  <mode rating="1" name="Human&#160;Resources">
   <skill name="Contacts"  cost="1"/>
   <skill name="Deceive"   cost="2"/>
   <skill name="Empathy"   cost="3"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Rapport"   cost="2"/>
   <skill name="Will"      cost="1"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="TBD1">TBD1</stunt>
  <stunt name="TBD2">TBD2</stunt>
  <stunt name="TBD3">TBD3</stunt>
  <stunt name="TBD4">TBD4</stunt>
  <stunt name="TBD5">TBD5</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/cpt_america.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
  <id>
    <charname>Steve Rogers / Cpt. America</charname>
    <playername>Supporting NPC</playername>
    <affiliation>Strategic Scientific Reserve</affiliation>
    <description>Specifically the version from Cpt. America: The First Avenger</description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">
    The Sentinel of Liberty
  </aspect>
    <aspect type="Mode" mode-name="Super&#160;Soldier">
    Just a Kid From Brooklyn
  </aspect>
    <aspect type="Mode" mode-name="Soldier">
    "I Don't Like Bullies. I Don't Care Where They're From."
  </aspect>
    <aspect type="Mode" mode-name="Action">
    "I Can Do This All Day."
  </aspect>
    <aspect type="Omega">
    &#160;
  </aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Super&#160;Soldier" stress-type="physical">
      <!-- ARRPG pg91 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Contacts" cost="1"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Rapport" cost="1"/>
      <skill name="Stealth" cost="2"/>
      <skill name="Tactics" cost="0"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="2" name="Soldier" stress-type="mental">
      <!-- ARRPG pg91 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Contacts" cost="1"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Tactics" cost="0"/>
      <skill name="Vehicles" cost="2"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="1" name="Action">
      <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Provoke" cost="1"/>
      <skill name="Vehicles" cost="2"/>
    </mode>
  </skills>
  <stunts>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <gadget name="Cap's Shield">
      <function>Throwable Vibranium Disc</function>
      <flaws>
        <flaw>Have to Hold It or Throw It, But Not Both</flaw>
      </flaws>
      <benefits>
        <benefit cost="1" name="Deflects a Machine Gun">
          +2 to Defend with Combat against firearms
        </benefit>
        <benefit cost="1" name="Swats a Grenade">
          +2 to Create an Advantage with Athletics when the shield could be narrated as useful
          (swatting a grenade, smashing through a door or window, etc.)
        </benefit>
      </benefits>
    </gadget>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/felicity_smoak.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
  <id>
    <charname>Felicity Smoak</charname>
    <playername>Proto-NPC</playername>
    <affiliation>Arrow</affiliation>
    <description>Kind of looks like Emily Bett Rickards. With glasses.</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Adorkable Hacker</aspect>
    <aspect type="Mode" mode-name="Science">Computers are TV Magic</aspect>
    <aspect type="Mode" mode-name="Banter">Did I Really Just Say That?</aspect>
    <aspect type="Mode" mode-name="Action">Hostage Got the Drop on You</aspect>
    <aspect type="Omega">No, Actually, I'm Jewish</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Computer Science"     cost="0" add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <!--
       Specialize one trained skill.  Computer Science
       Focus one trained skill.
       Specialize one focused skill.
  -->
    <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1" add="2"/> <!-- All Standard Modes improvement -->
      <skill name="Will"     cost="1"/>
    </mode>
    <mode rating="1" name="Action" stress-type="physical"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Admin Access">
      Use Computer Science instead of Burglary to overcome computerized security systems.
    </stunt>
    <stunt name="There's An Algorithm For That">
      When using a technological device that has a computerized component - even a single microchip -
      spend a fate point to operate it using Computer Science instead of whatever other skill would
      normally apply until the end of the scene.
    </stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
  Regardless of what modes you have, if they're all standard modes you get ONE of the following improvements:
  X Specialize one trained skill. Rapport

  If one of your modes is Science, also apply ALL of the following improvements:
  X Specialize one trained skill. Computer Science
  * Focus one trained skill.
  * Specialize one focused skill.
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/sherlock_holmes.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "./atomic-robo.dtd">
<character>
 <id>
  <charname>Sherlock Holmes</charname>
  <playername>From the 2010- BBC series</playername>
  <affiliation>Dr. John Watson; Baker St. Irregulars</affiliation>
  <description>Tall, dark hair, clean shaven. Usually in a long black wool coat.</description>
 </id>
 <current-fate-points>5</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept" signature="true">Consulting Detective</aspect>
  <aspect type="Mode" mode-name="Consulting&#160;Detective">The Police Come To Me When They're Out Of Their Depth...Which Is Always</aspect>
  <aspect type="Mode" mode-name="Action">Manic and Easily Bored</aspect>
  <aspect type="Mode" mode-name="Science">Why Can't You People Just Observe?</aspect>
  <aspect type="Omega">High-Functioning Sociopath</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Consulting&#160;Detective" stress-type="mental">
   <skill name="Burglary"  cost="1"/>
   <skill name="Contacts"  cost="1"/>
   <skill name="Deceive"   cost="2"/>
   <skill name="Forensics" cost="0" add="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Provoke"   cost="1"/>
   <skill name="Will"      cost="1" add="1"/> <!-- specialize one focused skill, pg34 -->
  </mode>
  <mode rating="2" name="Action" stress-type="physical">
   <skill name="Athletics" cost="2" add="1"/> <!-- focus 1 trained, pg34 -->
   <skill name="Combat"    cost="2"/>
   <skill name="Notice"    cost="1"/>
   <skill name="Physique"  cost="1"/>
   <skill name="Provoke"   cost="1"/>
   <skill name="Vehicles"  cost="2"/>
  </mode>
  <mode rating="1" name="Science">
   <skill name="Notice"    cost="1"/>
   <skill name="Will"      cost="1"/>
   <skill name="(all other Sciences)"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Mind Palace">
    Spend a Fate Point to make a suitable declaration predicated on eidetic memory.
  </stunt>
  <stunt name="The Science of Deduction">
    Use Notice instead of Empathy to discover a person's aspects via Create an Advantage,
      but only when doing so would further an investigation.
    Use Notice instead of Empathy to discern lies and deceptions via Defend,
      but only when doing so would further an investigation.
    Both at a cost (typically offending people or not understanding emotional bonds).
  </stunt>
  <stunt name="&#160;">&#160;</stunt>
  <stunt name="&#160;">&#160;</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
 <!--
  If one of your modes is Science, however, apply all of the following improvements:
  * Specialize one trained skill. (Forensics w/in Science).
  * Focus one trained skill (Athletics w/in Action).
  * Specialize one focused skill (Will w/in Consulting Detective).
 -->
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/oliver_queen.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
  <id>
    <charname>Oliver Queen</charname>
    <playername>Proto-NPC</playername>
    <affiliation>Arrow</affiliation>
    <description>Kind of looks like Stephen Amell</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Billionaire Frat Boy Turned Vigilante</aspect>
    <aspect type="Mode" mode-name="The&#160;Hood">Cleaning Up the Sins of the Queen Family</aspect>
    <aspect type="Mode" mode-name="Intrigue">Comfortable In Many Skins</aspect>
    <aspect type="Mode" mode-name="Survivor">That Which Doesn't Kill Me Makes Me More Fucked Up</aspect>
    <aspect type="Omega">(Over?)Protective of WOMEN I Love</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="The&#160;Hood" stress-type="split"> <!-- Vigilante, ARRPG pg267 s/Notice/Deceive/ -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2" add="2"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Provoke"   cost="1" add="1"/>
      <skill name="Vehicles"  cost="2"/>
      <skill name="Will"      cost="1"/>
    </mode>
    <mode rating="2" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
    </mode>
    <mode rating="1" name="Survivor" stress-type="physical"> <!-- ARRPG pg256 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1" add="1"/>
      <skill name="Will"      cost="1"/>
      <!-- 5 pts of Improvements -->
      <!-- 3 for Combat, 1 each for Provoke, Physique -->
    </mode>
  </skills>
  <stunts>
    <stunt name="Archer">+2 to Attack with Combat when firing a bow</stunt>
    <stunt name="Trick Arrows">+2 to Create an Advantage with Combat when firing a bow</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>
