=== kbaird/Fate-XSLT/characters/Jadepunk/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, aspects, professions, assets, consequences?)>
  <!ATTLIST character custom-css CDATA #IMPLIED>

  <!ELEMENT id (charname, playername, story)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT story (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base    CDATA #REQUIRED>
    <!ATTLIST refresh current CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (Portrayal|Background|Inciting-Incident|Belief|Trouble) #REQUIRED>

  <!ELEMENT professions (profession*)>
    <!ELEMENT profession (#PCDATA)>
    <!ATTLIST profession name   CDATA #REQUIRED>
    <!ATTLIST profession rating CDATA #REQUIRED>

  <!ELEMENT assets (asset*)>
    <!ELEMENT asset (features*, flaws*, notes?)>
    <!ATTLIST asset function       CDATA #IMPLIED>
    <!ATTLIST asset guiding-aspect CDATA #IMPLIED>
    <!ATTLIST asset name           CDATA #REQUIRED>
    <!ATTLIST asset type           CDATA #REQUIRED>

    <!ELEMENT features (feature*)>
      <!ELEMENT feature (#PCDATA)>
      <!--
           For benefits that can be expressed as a simple integer quantity, even if interpreted
           Limited, for example
      -->
      <!ATTLIST feature bonus      CDATA #IMPLIED>
      <!-- For benefits that require text, as opposed to a simple integer quanity -->
      <!ATTLIST feature effect     CDATA #IMPLIED>
      <!ATTLIST feature type
        (Aspect|Creation-Roll|Exceptional|Flexible|Focus|Harmful|Independent|
         Numerous|Professional|Protective|Resilient|Sturdy|Talented)
      #REQUIRED>
      <!-- Specifically for Focus: -->
      <!ATTLIST feature profession CDATA #IMPLIED>
      <!-- Specifically for Professional: -->
      <!ATTLIST feature main-profession   CDATA #IMPLIED>
      <!ATTLIST feature other-professions CDATA #IMPLIED>

    <!ELEMENT flaws (flaw*)>
      <!--
           For penalties that can be expressed as a simple integer quantity, even if interpreted
           Focus, Harmful, Protective, and Sturdy
      -->
      <!ATTLIST flaw bonus  CDATA #IMPLIED>
      <!ELEMENT flaw (#PCDATA)>
      <!-- For penalties that require text, as opposed to a simple integer quanity -->
      <!ATTLIST flaw effect CDATA #IMPLIED>
      <!ATTLIST flaw type (Consuming|Creation-Roll|Demanding|
                           Limited|Situational|Troubling) #REQUIRED>

    <!ELEMENT notes (#PCDATA)>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

=== kbaird/Fate-XSLT/characters/Jadepunk/cheetah.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Fugyara Min, Fastest Woman Alive</charname>
    <playername>Jacob Possin</playername>
    <story>
Min was one of the all time great relic hunters. She had robbed dozens of tombs on four
continents. Until she was betrayed. One of her rivals spread the word of a great lost city,
deep in the jungle south of Ahlmac territory. There were claims of Ruby Skulls and pyramids
of gold. The rival, Tobias Schmidt, did not spread these rumors for Min's benefit, no. He
spread them in the court of her largest patron, Inoue Shen. Shen ignored Min's warnings that
this was a trap and sent her to gather these riches.

In the harshest jungle, far from civilization, walking into what she knew to be a trap, Min
made a mistake. She dropped her compass. Of such small mistakes, mighty catastrophes grow.
This was one such mistake. Unable to make an accurate bearing she was forced to use the sun
and stars. In the deepest jungle, she got turned around, she became lost. Wandering for days
without proper supplies, she was becoming dehydrated and delirious. In this state she came
upon an ancient Teltac temple to Cicoh Chac, god of the Divine Wind and blood sacrifice.

Within the temple she drank of the holy waters and ate of the sacred mushroom. While in an
ecstatic state, brought about by her exhaustion and the mushrooms, she had a great vision of
the god Cicoh Chac. It came to her in the form of Spotted Panther and spoke of many things.
Dark secrets were revealed to Min and she accepted a great burden. She would become Cicoh
Chac's will made manifest. She donned the sacred garb of the Teltac Warrior Priests and set
out to find a new empire for her dark master.

In Kausao City the people will listen to anyone who gives them hope. Min has done more than
that, she has given them a twisted sense of power. She leads a small cult of the
underclasses, they feed her information and when the need strikes they bring to her a blood
sacrifice. Within her small district she has built a kingdom of blood. Right now it is
beneath the notice of those in power. On the day they do take notice, pray that it is not to
late. Min dreams of a city awash in blood and fear. She dreams of a burning empire from
horizon to horizon.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Jaguar Queen of the Panther Cult</aspect>
    <aspect type="Background">History Exists to Grant Me Power</aspect>
    <aspect type="Inciting-Incident">I am His Will Made Flesh</aspect>
    <aspect type="Belief">May His Shadow Fall Over All the World</aspect>
    <aspect type="Trouble">Things are Moving Too Slowly</aspect>
  </aspects>
  <professions>
    <profession rating="2" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="1" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="1" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Sacred Panther Cloak" function="Holy Cloak of Speed" type="Device">
      <features>
        <feature type="Exceptional" effect="can appear and disappear from a scene at will provided she can run"/>
        <feature type="Focus"       bonus="2" profession="Explorer"/>
        <feature type="Focus"       bonus="1" profession="Fighter"/>
        <feature type="Protective"  bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when wearing the cloak"/>
        <flaw type="Troubling"   effect="Voices in my head make me irrational"/>
      </flaws>
      <notes>
    The ancient Teltac high priests had cloaks made from the skins of the holy panthers, they
    would thread blue and white jade into the cloaks to aid in speed and stealth. This cloak is
    one of the last in existence, and makes Min the fastest biped on the planet.
      </notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
Fugyara Min, Fastest Woman Alive

Min was one of the all time great relic hunters. She had robbed dozens of tombs on four
continents. Until she was betrayed. One of her rivals spread the word of a great lost city,
deep in the jungle south of Ahlmac territory. There were claims of Ruby Skulls and pyramids
of gold. The rival, Tobias Schmidt, did not spread these rumors for Min's benefit, no. He
spread them in the court of her largest patron, Inoue Shen. Shen ignored Min's warnings that
this was a trap and sent her to gather these riches.

In the harshest jungle, far from civilization, walking into what she knew to be a trap, Min
made a mistake. She dropped her compass. Of such small mistakes, mighty catastrophes grow.
This was one such mistake. Unable to make an accurate bearing she was forced to use the sun
and stars. In the deepest jungle, she got turned around, she became lost. Wandering for days
without proper supplies, she was becoming dehydrated and delirious. In this state she came
upon an ancient Teltac temple to Cicoh Chac, god of the Divine Wind and blood sacrifice.

Within the temple she drank of the holy waters and ate of the sacred mushroom. While in an
ecstatic state, brought about by her exhaustion and the mushrooms, she had a great vision of
the god Cicoh Chac. It came to her in the form of Spotted Panther and spoke of many things.
Dark secrets were revealed to Min and she accepted a great burden. She would become Cicoh
Chac's will made manifest. She donned the sacred garb of the Teltac Warrior Priests and set
out to find a new empire for her dark master.

In Kausao City the people will listen to anyone who gives them hope. Min has done more than
that, she has given them a twisted sense of power. She leads a small cult of the
underclasses, they feed her information and when the need strikes they bring to her a blood
sacrifice. Within her small district she has built a kingdom of blood. Right now it is
beneath the notice of those in power. On the day they do take notice, pray that it is not to
late. Min dreams of a city awash in blood and fear. She dreams of a burning empire from
horizon to horizon.

Portrayal: Jaguar Queen of the Panther Cult
Background: History exists to grant me power
Inciting Incident: I am his will made flesh
Belief: May his shadow fall over all the world
Trouble: Things are moving too slowly

Professions: Explorer +3, Aristocrat and Scholar +2, Scoundrel and Fighter +1, Engineer +0

Assets
  Device: Sacred Panther Cloak
    The ancient Teltac high priests had cloaks made from the skins of the holy panthers, they
    would thread blue and white jade into the cloaks to aid in speed and stealth. This cloak is
    one of the last in existence, and makes Min the fastest biped on the planet.

    Function Aspect: Holy Cloak of Speed
    Features: Exceptional(can appear and disappear from a scene at will provided she can run),
    Focus 4(Fighter +2 and Explorer +2), Protective 2(reduce incoming shift value of an attack
      against you by two)
    Flaws: Situational(only when wearing the cloak), Troubling(Voices in my head make me
      irrational)

Refresh: 3
-->

=== kbaird/Fate-XSLT/characters/XiǎoJiāhuo/governor.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "./Jadepunk/character.dtd">
<character>
  <id>
    <charname>The Governor of Kausao City</charname>
    <playername>Jadepunk NPC</playername>
    <story>
      Rose to power through a balanced approach toward the Great Nations, maintaining it for 20 years.
      Had his underworld contacts cause public disorder to gain public support for declaration of martial law.
    </story>
  </id>
  <refresh base="10"/>
  <aspects>
    <aspect type="Portrayal">Longest-Serving Governor of Kausao City</aspect>
    <aspect type="Background">Unanimous Support Within the Council of Nine</aspect>
    <aspect type="Inciting-Incident">Engineered Martial Law via Corruption</aspect>
    <aspect type="Belief">The People Deserve Strong Leadership</aspect>
    <aspect type="Trouble">江湖 Terrorists are a Nuisance</aspect>
  </aspects>
  <professions>
    <profession rating="5" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="0" name="Fighter"/>
    <profession rating="3" name="Scholar"/>
    <profession rating="4" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="I Have Them in the Palm of My Hand" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Aristocrat"/>
        <feature type="Focus" bonus="2" profession="Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when dealing with the Council of Nine"/>
      </flaws>
      <notes>See pg19</notes>
    </asset>
    <asset name="Underworld Contacts" guiding-aspect="Inciting-Incident" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Aristocrat"/>
        <feature type="Focus" bonus="2" profession="Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when dealing with organized criminals"/>
      </flaws>
      <notes>See pg19</notes>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/XiǎoJiāhuo/tran_van_duc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character custom-css="tran_van_duc">
  <id>
    <charname nickname="Đức">Trần Văn Đức / 陈文德 / "Ancient Culture Virtue"</charname>
    <playername>Kevin Baird</playername>
    <story>
      Đức was part of the unsuccessful resistance against the Túyàngan invaders in the neighboring nation of Đại Nam (大南, "Big South").
      He has since relocated, along with a sizeable Đạinamese community, attempting to rebuild in Kausao City, with the eventual dream of
      liberating Đạinam from the 图样人 devils.
      (文 is a very typical male Đạinamese middle name, and the custom is to refer to one by personal name, like Đức).
      I see the Đạinamese community in Kausao as having several parallels to the Tauron community in Caprica City.
      The Browncoat analogy applies more to Đức and some others as individuals.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Đạinamese Browncoat</aspect>
    <aspect type="Background">Advance Scout in the 101st Partisans</aspect>
    <aspect type="Inciting-Incident">We Lost Because We Didn't Understand the Enemy</aspect>
    <aspect type="Belief">Everyone Deserves Freedom - Even 图样人</aspect>
    <aspect type="Trouble">Ha'la'tha - Always Faithful to the Soil</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="1" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Expatriate Đạinamese Community" function="Eyes, Ears, General Favors" type="Ally">
      <features>
        <feature type="Professional" bonus="2" main-profession="Aristocrat" other-professions="Scholar"/>
        <feature type="Numerous"     bonus="3"/>
        <feature type="Resilient"    bonus="1"/>
        <feature type="Sturdy"       bonus="1"/>
        <feature type="Independent"/>
      </features>
      <flaws>
        <flaw type="Troubling" effect="Expects Đức to be a Community Leader"/>
        <flaw type="Troubling" effect="Only in or near Đạinamtown"/>
        <flaw type="Troubling" effect="Nothing Too Dangerous"/>
      </flaws>
      <notes>I figure it's quite large, but the Numerous reflects a sub-group available to help at any given time.</notes>
    </asset>
    <asset name="Jade Tattoo" function="Blue Jade Tattoo of Detection" type="Device">
      <features>
        <feature bonus="3" type="Focus" profession="Scholar"/>
      </features>
      <flaws>
        <flaw type="Troubling"   effect="Easily Identifiable"/>
        <flaw type="Situational" effect="Scholar can only be used for sensing surroundings"/>
      </flaws>
      <notes>Obvious, like Mike Tyson's face tattoo, and IDs Đức as a 'Browncoat'.</notes>
    </asset>
    <asset name="Knowledge is Power" guiding-aspect="Inciting-Incident" type="Technique">
      <features>
        <feature type="Focus" profession="Scholar" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only About Đạinamese, Túyàngan, or Kausaoan History"/>
      </flaws>
    </asset>
    <asset name="A Leaf in the Wind" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" bonus="4" profession="Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Avoid Detection"/>
      </flaws>
    </asset>
    <asset name="The Slow Blade Penetrates the Shield" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" bonus="4" profession="Fighter"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Attack"/>
        <flaw type="Situational" effect="Only with a bladed weapon"/>
        <flaw type="Situational" effect="Only vs. a Jade-enhanced defense"/>
      </flaws>
      <notes>Yes, I stole this from Dune.</notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
     http://en.wikipedia.org/wiki/Vietnamese_name
     http://en.wikipedia.org/wiki/Tr%E1%BA%A7n
     http://en.wiktionary.org/wiki/%E5%BE%B7#Vietnamese
     http://en.battlestarwiki.org/wiki/Ha%27la%27tha
-->

=== kbaird/Fate-XSLT/characters/Jadepunk/matt_murdock.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>Matt Murdock</charname>
    <playername>adapted character</playername>
    <story>
      Son of a boxer, lost his sight rescuing an old man, kept his promise to his
      dad to have a white collar job.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Lawyer by Day; Devil of Hell's Kitchen by Night</aspect>
    <aspect type="Background">Blind, Heightened Senses; Trained by Stick</aspect>
    <aspect type="Inciting-Incident">Battlin' Jack Murdock Never Quit</aspect>
    <aspect type="Belief">Fisk Must Not Control Hell's Kitchen</aspect>
    <aspect type="Trouble">What's a Good Catholic Boy to Do?</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="1" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Can't Pin Him Down" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" profession="Fighter" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Defend"/>
      </flaws>
    </asset>
    <asset name="Defang the Snake" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Exceptional" effect="Disarm an opponent when you succeed on defense"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only on a Success With Style"/>
        <flaw type="Limited" bonus="1"/>
      </flaws>
    </asset>
    <asset name="Takes a Beating" guiding-aspect="Inciting-Incident" type="Technique">
      <features>
        <feature type="Protective" bonus="1"/>
      </features>
      <flaws>
        <flaw type="Demanding" effect="Requires Fair (+2) Fighter roll"/>
        <flaw type="Situational" effect="Ineffective Against Esoteric Martial Artists, Like Ninjas"/>
      </flaws>
    </asset>
    <asset name="Where the Hell Did He Come From?" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" profession="Scoundrel" bonus="3"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only for Creating an Advantage"/>
        <flaw type="Situational" effect="Only to sneak up on or past someone"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/dilar.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>Dilar Hanania</charname>
    <playername>Jennifer Cornish</playername>
    <story>
      Owns a secret Black Jade mine under her family's more modest "Wayne Manor".
      Someone has developed an anti-psychotic drug using Black and Green Jade that
      has helped her schizophrenic younger sister. Owns The Blooming Lotus, a drug
      den in the Terminal Strip neighborhood of Kausao City under the pseudonym of
      "Madame Lotus". Relationship w/Jianghu (江湖; lit. "rivers and lakes") is unclear.
      Probably travels in upper crust social circles. Employs Hamza Abu-Talat and Steffan
      Gilios at The Blooming Lotus. Naramel.
      The mining company owned by her family is smaller than any of the big 5 from pg96.
      Speaks Naramel natively, Kaiyu at Junior High student level, and Túyàngan and Aerish
      functionally as a glamorous rich person who's not trying too hard.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Daughter of Old Mining Money</aspect>
    <aspect type="Background">I Have Friends on the Council</aspect>
    <aspect type="Inciting-Incident">Who's After the Formula, and Why?</aspect>
    <aspect type="Belief">I Have to Take Care of My Sister</aspect>
    <aspect type="Trouble">Secret Owner of a Kausao Speakeasy</aspect>
  </aspects>
  <professions>
    <profession rating="3" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="0" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Cutting Remarks" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Exceptional" effect="Target may not check a Stress Box"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only for Attacks with Aristocrat"/>
      </flaws>
    </asset>
    <!--
    <asset name="Ear to the Ground" guiding-aspect="Trouble" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Aristocrat"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when using your network to find information"/>
      </flaws>
    </asset>
    -->
    <asset name="Let's Make a Deal" guiding-aspect="Trouble" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Aristocrat"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Create Advantages on an NPC who is someone else's boss"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/Jadepunk/james_gordon.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>James Gordon</charname>
    <playername>adapted character</playername>
    <story>
      An honest firebrand at the GCPD.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">One of the Only Good Cops on the GCPD</aspect>
    <aspect type="Background">This Badge Should Mean Something</aspect>
    <aspect type="Inciting-Incident">Harvey Asked Me to Kill Cobblepot. I Pretended to Go Along.</aspect>
    <aspect type="Belief">I Won't Stop Until GCPD Is Cleaned Up</aspect>
    <aspect type="Trouble">Doesn't Know When To Keep Quiet</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="1" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Follow the Clues" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" profession="Scholar" bonus="3"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only When Creating an Advantage"/>
        <flaw type="Situational" effect="Only When Investigating a Crime"/>
      </flaws>
    </asset>
    <asset name="Standard-issue sidearm" function="Woo Fu" type="Device">
      <features>
        <feature type="Harmful" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Demanding" effect="(requires an action to reload after a lot of shooting)"/>
      </flaws>
    </asset>
    <asset name="Tell Me What You Know" guiding-aspect="Trouble" type="Technique">
      <features>
        <feature type="Focus" profession="Aristocrat" bonus="3"/>
      </features>
      <flaws>
        <flaw type="Troubling"   effect="Who Do I Piss Off Today?"/>
        <flaw type="Situational" effect="Only When Investigating a Crime"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/wu_ming_shu.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname nickname="五明数">Wǔ míng shù</charname>
    <playername>Michael Wood</playername>
    <story>
      An alchemist / brewer of elixirs &amp; concoctions.
      Probably 图样人。Mysteriously employed by [Hawthorne Droneworks],
      which specializes in Jade-powered drones. Why are they
      employing an alchemist?
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Túyàngan Alchemist</aspect>
    <aspect type="Background">&#160;</aspect>
    <aspect type="Inciting-Incident">Why is a Droneworks employing an Alchemist?</aspect>
    <aspect type="Belief">There are People Involved</aspect>
    <aspect type="Trouble">&#160;</aspect>
  </aspects>
  <professions>
    <profession rating="3" name="Aristocrat"/>
    <profession rating="2" name="Engineer"/>
    <profession rating="&#160;" name="Explorer"/>
    <profession rating="&#160;" name="Fighter"/>
    <profession rating="&#160;" name="Scholar"/>
    <profession rating="&#160;" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Alchemist" guiding-aspect="Portrayal" type="Technique">
      <features>
        <feature type="Focus" profession="Engineer" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when brewing Jade-infused potion Devices"/>
      </flaws>
    </asset>
    <asset name="XXX" guiding-aspect="Inciting-Incident" type="Technique">
      <features>
        <feature type="Flexible" effect="Use Aristocrat instead of Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="When trying to conceal information about Jade research"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/chen_daiyu.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>Chen Daiyu</charname>
    <playername>Phil Bernard</playername>
    <story>&#160;</story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Practioner of the Ghost Serpent Style</aspect>
    <aspect type="Background"></aspect>
    <aspect type="Inciting-Incident">Witnessed the murder of her 江湖 master</aspect>
    <aspect type="Belief">I will "rest" when my master is avenged</aspect>
    <aspect type="Trouble">Extremely stubborn</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="3" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Jade Tattoo" function="Blue Jade Tattoo of Stealth" type="Device">
      <features>
        <feature type="Focus" bonus="4" profession="Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only vs. Jade-enhanced detection"/>
      </flaws>
    </asset>
    <asset name="The Downstairs Help" function="Eyes, Ears, General Favors" type="Ally">
      <features>
        <feature type="Professional" bonus="2" main-profession="Aristocrat" other-professions="Scholar"/>
        <feature type="Resilient"    bonus="1"/>
        <feature type="Independent"/>
        <feature type="Sturdy"       bonus="1"/>
      </features>
      <flaws>
        <flaw type="Troubling"   effect="Expects Quid Pro Quo"/>
        <flaw type="Situational" effect="Only Within Estates of the Wealthy"/>
        <flaw type="Situational" effect="Nothing Too Dangerous"/>
      </flaws>
      <notes>A moderately large group, but no Numerous, as only one person is available to help at any given time.</notes>
    </asset>
    <asset name="Defang the Snake" guiding-aspect="Portrayal" type="Technique">
      <features>
        <feature type="Exceptional" effect="Reactively disarm an opponent who missed you in combat"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only on a Success With Style"/>
        <flaw type="Situational" effect="Only When defending against an opponent wielding a melee weapon"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>
