=== kbaird/Fate-XSLT/characters/Jadepunk/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, aspects, professions, assets, consequences?)>
  <!ATTLIST character custom-css CDATA #IMPLIED>

  <!ELEMENT id (charname, playername, story)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT story (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base    CDATA #REQUIRED>
    <!ATTLIST refresh current CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (Portrayal|Background|Inciting-Incident|Belief|Trouble) #REQUIRED>

  <!ELEMENT professions (profession*)>
    <!ELEMENT profession (#PCDATA)>
    <!ATTLIST profession name   CDATA #REQUIRED>
    <!ATTLIST profession rating CDATA #REQUIRED>

  <!ELEMENT assets (asset*)>
    <!ELEMENT asset (features*, flaws*, notes?)>
    <!ATTLIST asset function       CDATA #IMPLIED>
    <!ATTLIST asset guiding-aspect CDATA #IMPLIED>
    <!ATTLIST asset name           CDATA #REQUIRED>
    <!ATTLIST asset type           CDATA #REQUIRED>

    <!ELEMENT features (feature*)>
      <!ELEMENT feature (#PCDATA)>
      <!--
           For benefits that can be expressed as a simple integer quantity, even if interpreted
           Limited, for example
      -->
      <!ATTLIST feature bonus      CDATA #IMPLIED>
      <!-- For benefits that require text, as opposed to a simple integer quanity -->
      <!ATTLIST feature effect     CDATA #IMPLIED>
      <!ATTLIST feature type
        (Aspect|Creation-Roll|Exceptional|Flexible|Focus|Harmful|Independent|
         Numerous|Professional|Protective|Resilient|Sturdy|Talented)
      #REQUIRED>
      <!-- Specifically for Focus: -->
      <!ATTLIST feature profession CDATA #IMPLIED>
      <!-- Specifically for Professional: -->
      <!ATTLIST feature main-profession   CDATA #IMPLIED>
      <!ATTLIST feature other-professions CDATA #IMPLIED>

    <!ELEMENT flaws (flaw*)>
      <!--
           For penalties that can be expressed as a simple integer quantity, even if interpreted
           Focus, Harmful, Protective, and Sturdy
      -->
      <!ATTLIST flaw bonus  CDATA #IMPLIED>
      <!ELEMENT flaw (#PCDATA)>
      <!-- For penalties that require text, as opposed to a simple integer quanity -->
      <!ATTLIST flaw effect CDATA #IMPLIED>
      <!ATTLIST flaw type (Consuming|Creation-Roll|Demanding|
                           Limited|Situational|Troubling) #REQUIRED>

    <!ELEMENT notes (#PCDATA)>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

=== kbaird/Fate-XSLT/characters/Jadepunk/general_zod.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>General 肖 (Xiào), Master of the World</charname>
    <playername>Jacob Possin</playername>
    <story>
Twenty years ago a young popular general of the Tuyangan Army staged an ill fated coups attempt
on the throne. His rebel army was wiped out and he fled the country in disgrace. While he had
lost in his bid for power, General 肖 never gave up on his desire for power. His key to
victory came to him when he arrived in the Kingdom of Kent. Hiring himself out as a mercenary
he met the Lord Clark's chief engineer, Alexis Luthor. She was ambitious and amoral, much like
肖. Over the course of a year he managed to gain her confidence and together they
orchestrated one of the largest coups in recent history.
<!--
Since becoming High Lord of Kent, 肖 has dedicated his life to conquest. His people slave
away in the white jade mines and manufactories, building him a massive war fleet of skyships.
However, despite his successes, 肖 is still haunted by his failure. He lives in fear the the
son of Clark, the true ruler of Kent, will one day return and depose him. this thought keeps
him up nights. He cannot merely kill the man, as then he makes a martyr of him. he must capture
and subjugate this supposed rival. He must. 肖 has sent several teams of bounty hunters after
Johnathan Clark with this in mind. None have returned.
-->
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Wanna-be World Conqueror</aspect>
    <aspect type="Background">Master Of War</aspect>
    <aspect type="Inciting-Incident">Kneel Before 肖!</aspect>
    <aspect type="Belief">Only the Strong Shall Rule</aspect>
    <aspect type="Trouble">Temperamental Paranoid</aspect>
  </aspects>
  <professions>
    <profession rating="2" name="Aristocrat"/>
    <profession rating="0" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="3" name="Fighter"/>
    <profession rating="1" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Master of the Field of Battle" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Fighter"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when leading men in battle"/>
      </flaws>
      <notes>
  Despite his flaws, 肖 is a brilliant general. On the field, few can defeat him in direct
  conflict. He has studied all the great wars and military tactics ever recorded. He has,
  himself, been the leader in many campaigns. To go against 肖 in battle is a dangerous
  gambit.
      </notes>
    </asset>
    <asset name="Poison Fist Strike" guiding-aspect="Belief" type="Technique">
      <features>
        <feature type="Harmful" bonus="4"/>
      </features>
      <flaws>
        <flaw type="Troubling" effect="My Enemies Know My Moves"/>
      </flaws>
      <notes>
  肖 holds that strength in conflict is the most efficient way of winning. He believes this on
  both the large and the small scale. In a fight he will strike with such force that he has been
  known to penetrate even the strongest armor. This is known as his Poison Fist Strike.
      </notes>
    </asset>
    <asset name="Royal Armor of Kent" function="Green and White Jade Plate Armor" type="Device">
      <features>
        <feature type="Protective" bonus="2"/>
        <feature type="Resilient"/>
        <feature type="Resilient"/>
      </features>
      <flaws>
        <flaw type="Demanding" effect="Fighter vs. +2 to don or doff"/>
        <flaw type="Demanding" effect="Must be done after any scene in which the belt is used more than once"/>
      </flaws>
      <notes>
  The Armor of Kent has belonged to the Clark line for as long as any can remember. It was worn
  by the Kings of Kent in defense of the homeland only. It was said that the armor would
  protect Kent so longh as even one of the Clark line remains. When 肖 conquered Kent he
  began wearing the armor as a sign of his authority. However, to the people of Kent, the Bold
  S shaped seal on the chest is a reminder that one Clark still lives. It tells them that their
  is still hope.
      </notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
General Xiao, Master of the World
Twenty years ago a young popular general of the Tuyangan Army staged an ill fated coups attempt
on the throne. His rebel army was wiped out and he fled the country in disgrace. While he had
lost in his bid for power, General Xiao never gave up on his desire for power. His key to
victory came to him when he arrived in the Kingdom of Kent. Hiring himself out as a mercenary
he met the Lord Clark's chief engineer, Alexis Luthor. She was ambitious and amoral, much like
Xiao. Over the course of a year he managed to gain her confidence and together they
orchestrated the largest coups in recent history.

Since becoming High Lord of Kent, Xiao has dedicated his life to conquest. His people slave
away in the white jade mines and manufactories, building him a massive war fleet of skyships.
However, despite his successes, Xiao is still haunted by his failure. He lives in fear the the
son of Clark, the true ruler of Kent, will one day return and depose him. this thought keeps
him up nights. He cannot merely kill the man, as then he makes a martyr of him. he must capture
and subjugate this supposed rival. He must. Xiao has sent several teams of bounty hunters after
Johnathan Clark with this in mind. None have returned.

Portrayal: Wanna-be World Conqueror
Background: Master Of War
Inciting Incident: Kneel Before Xiao!
Belief: Only the Strong Shall Rule
Trouble: Temperamental Paranoid

Professions: Fighter +3, Scoundrel and Aristocrat +2, Explorer and Scholar +1, Engineer +0

Assets
Technique: Poison Fist Strike
  Xiao holds that strength in conflict is the most efficient way of winning. He believes this on
  both the large and the small scale. In a fight he will strike with such force that he has been
  known to penetrate even the strongest armor. This is known as his Poison Fist Strike.

  Guiding Aspect: Only the Strong Shall Rule
  Features: Harmful 4(Four extra harm on a successful strike)
  Flaws: Troubling(My Enemies Know My Moves)

Technique: Master of the Field of Battle
  Despite is flaws, Xiao is a brilliant general. On the field, few can defeat him in direct
  conflict. He has studied all the great wars and military tactics ever recorded. He has,
  himself, been the leader in many campaigns. To go against Xiao in battle is a dangerous
  gambit.

  Guiding Aspect: Master of War
  Features: Focus 2(+2 fighting)
  Flaws: Situational(only when leading men in battle)

Device: Royal Armor of Kent
  The Armor of Kent has belonged to the Clark line for as long as any can remember. It was worn
  by the Kings of Kent in defense of the homeland only. It was said that the armor would
  protect Kent so longh as even one of the Clark line remains. When Xiao conquered Kent he
  began wearing the armor as a sign of his authority. However, to the people of Kent, the Bold
  S shaped seal on the chest is a reminder that one Clark still lives. It tells them that their
  is still hope.

  Function Aspect: Green and White Jade Plate Armor
  Features: Protective 2(reduce incoming harm of successful attack by two), Resilient 2(two
    extra stress boxes)
  Flaws: Demanding(you must make a fighter roll vs a difficulty of +2 in order to put the armor
    on or take it off)
-->

=== kbaird/Fate-XSLT/characters/Jadepunk/batman.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Wei Baatarsai, The Bat</charname>
    <playername>Jacob Possin</playername>
    <story>
Baatarsai was born to the owner of one of the finest Jadetech Engineering firms in all of
Kausao, Wei-Tech Industrial. Over ten percent of all jade in the city was smelted in their
Refineries, and Wei-Tech innovations were used in all forms of Jadetech. Life was good for the
child Baatarsai, until that fateful night. On their way home from the opera his mother and
father were robbed and killed in front of his very eyes. On that day he swore an oath to put a
stop to all crime, so that no one else would ever need go through the pain he had just
suffered.

<!--
Raised by his loyal manservant, Peng An, young Baatarsai set out to accomplish his task. He
trained in martial arts, science, and psychology. In learning he discovered that crime was not
merely a problem, but a symptom of a larger problem. He knew that as a man he could not be what
the city needed. He would need to change the hearts of men, to do this he would need to become
a symbol. Bringing hope to the downtrodden and fear to the criminal element. He became the Bat.
A rumor in the night. A mad god that swooped down upon the guilty and freed the innocent. The
City Watch are often driven to distraction by the graffiti of the bat, written on walls and
buildings throughout the city. None suspect that the benevolent business man Wei Baatarsai is
this creature of the night. He makes sure to appear as an idle son of a rich man, uninterested
in anything but parties and women. Bon Vivant by day, Bat Vigilante by night.
-->
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Spirit of Justice</aspect>
    <aspect type="Background">Warrior Detective</aspect>
    <aspect type="Inciting-Incident">Let no one suffer as I have suffered</aspect>
    <aspect type="Belief">Fear and Violence keep the Criminals at bay</aspect>
    <aspect type="Trouble">The People Still Suffer</aspect>
  </aspects>
  <professions>
    <profession rating="1" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="0" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="3" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Master Detective" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Flexible" effect="Can use Scholar in place of Explorer"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when dealing with crime and crime scenes"/>
      </flaws>
      <notes>
Trained from an early age by Peng An in several forms of martial arts, Baatarsai has developed
his own unique style of fighting. It uses stealth and fear alongside sudden and brutal attacks
to take his opponents out with minimal danger. As a master of the Way of the Bat, Baatarsai can
read his opponents like a book and react with near superhuman speed to their actions.
      </notes>
    </asset>
    <asset name="Peng An" function="Wise and Loyal Manservant" type="Ally">
      <features>
        <feature type="Aspect"       effect="Master of the Martial Arts"/>
        <feature type="Professional" bonus="2" main-profession="Fighter" other-professions="Aristocrat, Scholar"/>
        <feature type="Resilient"/>
        <feature type="Resilient"/>
        <feature type="Sturdy"       bonus="1"/>
      </features>
      <flaws>
        <flaw type="Troubling" effect="The Bat's Hidden Weakness"/>
      </flaws>
      <notes>
A former master of the martial arts, An gave up fighting to become a man of peace. After the
death of his master, he sought to help you Baatarsai deal with his pain through the only
thing An knew might help. He trained the lad in every form of martial arts he knew. Never had
An seen a more gifted or dedicated pupil. Now he is old and he looks at Baatarsai's life's
work with no small amount of pride. Though he doesn't say, Baatarsai loves his mentor, and
fears for his safety now that the great work has begun.
      </notes>
    </asset>
    <asset name="Utility Belt" function="Utility Belt Full of Minor Jade devices" type="Device">
      <features>
        <feature type="Exceptional" effect="Invoke created Aspects with +3 instead of +2"/>
      </features>
      <flaws>
        <flaw type="Demanding" effect="1 Turn and an Engineer vs. +2"/>
        <flaw type="Demanding" effect="Must be done after any scene in which the belt is used more than once"/>
      </flaws>
      <notes>
As the sole owner of Wei-Tech Industrial, Baatarsai has access to a great many jadetech
innovations. He carries a variety of cutting edge tools in a specially designed belt. It is
the rare situation that he is not prepared for.
      </notes>
    </asset>
    <asset name="The Way of the Bat" guiding-aspect="Belief" type="Technique">
      <features>
        <feature type="Focus" bonus="1" profession="Fighter"/>
        <feature type="Focus" bonus="1" profession="Scoundrel"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only in the shadows and darkness"/>
      </flaws>
      <notes>
Trained from an early age by Peng An in several forms of martial arts, Baatarsai has developed
his own unique style of fighting. It uses stealth and fear alongside sudden and brutal attacks
to take his opponents out with minimal danger. As a master of the Way of the Bat, Baatarsai can
read his opponents like a book and react with near superhuman speed to their actions.
      </notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
Wei Baatarsai, The Bat
Baatarsai was born to the owner of one of the finest Jadetech Engineering firms in all of
Kausao, Wei-Tech Industrial. Over ten percent of all jade in the city was smelted in their
Refineries, and Wei-Tech innovations were used in all forms of Jadetech. Life was good for the
child Baatarsai, until that fateful night. On their way home from the opera his mother and
father were robbed and killed in front of his very eyes. On that day he swore an oath to put a
stop to all crime, so that no one else would ever need go through the pain he had just
suffered.

Raised by his loyal manservant, Peng An, young Baatarsai set out to accomplish his task. He
trained in martial arts, science, and psychology. In learning he discovered that crime was not
merely a problem, but a symptom of a larger problem. He knew that as a man he could not be what
the city needed. He would need to change the hearts of men, to do this he would need to become
a symbol. Bringing hope to the downtrodden and fear to the criminal element. He became the Bat.
A rumor in the night. A mad god that swooped down upon the guilty and freed the innocent. The
City Watch are often driven to distraction by the graffiti of the bat, written on walls and
buildings throughout the city. None suspect that the benevolent business man Wei Baatarsai is
this creature of the night. He makes sure to appear as an idle son of a rich man, uninterested
in anything but parties and women. Bon Vivant by day, Bat Vigilante by night.

Portrayal: Spirit of Justice
Background: Warrior Detective
Inciting Incident: Let no one suffer as I have suffered
Belief: Fear and Violence keep the Criminals at bay
Trouble: The People Still Suffer

Professions: Scoundrel +3, Fighter and Scholar +2, Engineer and Aristocrat +1, Explorer +0

Assets
Technique: The Way of the Bat
Trained from an early age by Peng An in several forms of martial arts, Baatarsai has developed
his own unique style of fighting. It uses stealth and fear alongside sudden and brutal attacks
to take his opponents out with minimal danger. As a master of the Way of the Bat, Baatarsai can
read his opponents like a book and react with near superhuman speed to their actions.

Guiding Aspect: Fear and Violence Keep the Criminals at Bay
Features: Focus 1(+1 to fighter), Focus +1(Scoundrel +1)
  Flaws: Situational(only in the shadows and darkness)

  Device: Utility Belt
  As the sole owner of Wei-Tech Industrial Baatarsai has access to a great many jadetech
  innovations. He carries a variety of cutting edge tools in a specially designed belt. It is
  the rare situation that he is not prepared for.

  Function aspect: Utility Belt Full of Minor Jade devices
  Features: Exceptional(when utilizing aspects related to gear gain a +3 rather than the normal
    +2)
  Flaws: Demanding 2(Must take a turn and an engineering roll vs +2 difficulty in order to load
    up your belt, must be done after any scene where you utilize the utility belt more than
    once)

  Technique: Master Detective
  Guiding Aspect: Warrior Detective
  Features: Flexible(can use scholar in place of explorer)
  Flaws: Situational(only when dealing with crime and crime scenes)

  Ally: Peng An
  A former master of the martial arts, An gave up fighting to become a man of peace. After the
  death of his master, he sought to help you Baatarsai deal with his pain through the only
  thing An knew might help. He trained the lad in every form of martial arts he knew. Never had
  An seen a more gifted or dedicated pupil. Now he is old and he looks at Baatarsai's life's
  work with no small amount of pride. Though he doesn't say, Baatarsai loves his mentor, and
  fears for his safety now that the great work has begun.

  Function Aspect: Wise and Loyal Manservant
  Features: Aspect(Master of the Martial Arts), Professional 4(Scholar +1, Fighter +2,
    Aristocrat +1), Resilient 2(2 minor consequences), Sturdy(one Stress box)
  Flaws: Troubling(The Bat's Hidden Weakness)


  Refresh: 1
-->

=== kbaird/Fate-XSLT/characters/Jadepunk/mike_pc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>&#160;</charname>
    <playername>Michael Wood</playername>
    <story>
      An alchemist / brewer of elixirs &amp; concoctions.
      Probably 图样人。
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">&#160;</aspect>
    <aspect type="Background">&#160;</aspect>
    <aspect type="Inciting-Incident">&#160;</aspect>
    <aspect type="Belief">&#160;</aspect>
    <aspect type="Trouble">&#160;</aspect>
  </aspects>
  <professions>
    <profession rating="&#160;" name="Aristocrat"/>
    <profession rating="3" name="Engineer"/>
    <profession rating="&#160;" name="Explorer"/>
    <profession rating="&#160;" name="Fighter"/>
    <profession rating="&#160;" name="Scholar"/>
    <profession rating="&#160;" name="Scoundrel"/>
  </professions>
  <assets>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/Jadepunk/tran_van_duc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname nickname="Đức">Trần Văn Đức / 陈文德 / "Ancient Culture Virtue"</charname>
    <playername>Kevin Baird</playername>
    <story>
      Đức was part of the unsuccessful resistance against the Túyangan invaders in the neighboring nation of Đại Nam (大南, "Big South").
      He has since relocated, along with a sizeable Đạinamese community, attempting to rebuild in Kausao City, with the eventual dream of
      liberating Đạinam from the Túyangan devils.
      (文 is a very typical male Đạinamese middle name, and the custom is to refer to one by personal name, like Đức).
      I see the Đạinamese community in Kausao as having several parallels to the Tauron community in Caprica City.
      The Browncoat analogy applies more to Đức and some others as individuals.
    </story>
  </id>
  <refresh current="2">2</refresh>
  <aspects>
    <aspect type="Portrayal">Đạinamese Browncoat</aspect>
    <aspect type="Background">Advance Scout in the 101st Partisans</aspect>
    <aspect type="Inciting-Incident">We Lost Because We Didn't Understand the Enemy</aspect>
    <aspect type="Belief">Everyone Deserves Freedom - Even Túyangans</aspect>
    <aspect type="Trouble">Ha'la'tha - Always Faithful to the Soil</aspect>
  </aspects>
  <professions>
    <profession rating="0" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="1" name="Scoundrel"/>
  </professions>
  <assets>
    <asset guiding-aspect="Background" name="A Leaf in the Wind" type="Technique">
      <features>
        <feature type="Flexible" effect="Use Explorer instead of Scoundrel"/>
        <feature type="Focus"    bonus="2" profession="Explorer"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Avoid Detection"/>
      </flaws>
    </asset>
    <asset function="Eyes, Ears, General Favors" name="Expatriate Đạinamese Community" type="Ally">
      <features>
        <feature type="Independent"/>
        <feature type="Sturdy"       bonus="1"/>
        <feature type="Professional" bonus="2" main-profession="Aristocrat" other-professions="Scoundrel"/>
        <feature type="Resilient"    bonus="1"/>
        <feature type="Numerous"     bonus="5"/>
      </features>
      <flaws>
        <flaw type="Troubling" effect="Expects Đức to be a Community Leader"/>
        <flaw type="Troubling" effect="Only in or near Đạinamtown"/>
        <flaw type="Troubling" effect="Nothing Too Dangerous"/>
      </flaws>
    </asset>
    <asset guiding-aspect="Inciting-Incident" name="Knowledge is Power" type="Technique">
      <features>
        <feature type="Focus" profession="Scholar" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only About Đạinamese, Túyangan, or Kausaoan History"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
     http://en.wikipedia.org/wiki/Vietnamese_name
     http://en.wikipedia.org/wiki/Tr%E1%BA%A7n
     http://en.wiktionary.org/wiki/%E5%BE%B7#Vietnamese
     http://en.battlestarwiki.org/wiki/Ha%27la%27tha
-->
