=== kbaird/Fate-XSLT/characters/Jadepunk/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, aspects, professions, assets, consequences?)>
  <!ATTLIST character custom-css CDATA #IMPLIED>

  <!ELEMENT id (charname, playername, story)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT story (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base    CDATA #REQUIRED>
    <!ATTLIST refresh current CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (Portrayal|Background|Inciting-Incident|Belief|Trouble) #REQUIRED>

  <!ELEMENT professions (profession*)>
    <!ELEMENT profession (#PCDATA)>
    <!ATTLIST profession name   CDATA #REQUIRED>
    <!ATTLIST profession rating CDATA #REQUIRED>

  <!ELEMENT assets (asset*)>
    <!ELEMENT asset (features*, flaws*, notes?)>
    <!ATTLIST asset function       CDATA #IMPLIED>
    <!ATTLIST asset guiding-aspect CDATA #IMPLIED>
    <!ATTLIST asset name           CDATA #REQUIRED>
    <!ATTLIST asset type           CDATA #REQUIRED>

    <!ELEMENT features (feature*)>
      <!ELEMENT feature (#PCDATA)>
      <!--
           For benefits that can be expressed as a simple integer quantity, even if interpreted
           Limited, for example
      -->
      <!ATTLIST feature bonus      CDATA #IMPLIED>
      <!-- For benefits that require text, as opposed to a simple integer quanity -->
      <!ATTLIST feature effect     CDATA #IMPLIED>
      <!ATTLIST feature type
        (Aspect|Creation-Roll|Exceptional|Flexible|Focus|Harmful|Independent|
         Numerous|Professional|Protective|Resilient|Sturdy|Talented)
      #REQUIRED>
      <!-- Specifically for Focus: -->
      <!ATTLIST feature profession CDATA #IMPLIED>
      <!-- Specifically for Professional: -->
      <!ATTLIST feature main-profession   CDATA #IMPLIED>
      <!ATTLIST feature other-professions CDATA #IMPLIED>

    <!ELEMENT flaws (flaw*)>
      <!--
           For penalties that can be expressed as a simple integer quantity, even if interpreted
           Focus, Harmful, Protective, and Sturdy
      -->
      <!ATTLIST flaw bonus  CDATA #IMPLIED>
      <!ELEMENT flaw (#PCDATA)>
      <!-- For penalties that require text, as opposed to a simple integer quanity -->
      <!ATTLIST flaw effect CDATA #IMPLIED>
      <!ATTLIST flaw type (Consuming|Creation-Roll|Demanding|
                           Limited|Situational|Troubling) #REQUIRED>

    <!ELEMENT notes (#PCDATA)>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

=== kbaird/Fate-XSLT/characters/Jadepunk/superman.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Lord Johnathon Clark</charname>
    <playername>Jacob Possin</playername>
    <story>
The floating city of Kent was a bastion of peace and honor. Rich in white jade mines and a
place of high learning. It was ruled over by the ruling house, Clark. Then came the ambitious
General, Xiao, a mercenary who gathered power wherever he could. In one swift stroke he wiped
out the Clarks and took control of the city. The Lord Clark was able to get his son secreted
away prior to the attack. Now Johnathan lives as an exile in Kausao City. He found an ancient
temple deep beneath the earth and there found the power to stand against Xiao and bullies like
him.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Champion of the People</aspect>
    <aspect type="Background">True King of Kent</aspect>
    <aspect type="Inciting-Incident">House Destroyed, Family Dead</aspect>
    <aspect type="Belief">The Strong Must Protect the Weak</aspect>
    <aspect type="Trouble">I Cannot Save Them All</aspect>
  </aspects>
  <professions>
    <profession rating="2" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="3" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="1" name="Scholar"/>
    <profession rating="0" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Raiment of Rao" function="Ancient Power Suit" type="Device">
      <features>
        <feature type="Exceptional" effect="Allows you to fly, maneuver with Explorer"/>
        <feature type="Protective"  bonus="3"/>
        <feature type="Sturdy"      bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only in direct sunlight"/>
        <flaw type="Troubling" effect="Everyone wants the suit's secrets"/>
      </flaws>
      <notes>
        In the hidden temple of Rao, buried deep beneath the City, Johnathan discovered an ancient
        Jadetech Power Suit. It is revolutionary and beyond what most alchemists are capable of even
        in this age of enlightenment. When in direct sunlight the suit allows the wearer to ride the
        beams of light and a degree of invulnerability. It is a strange mixture of Blue, Red and
        Black jade. Since he first stepped into the sky over Kausao, the rich and the criminal have
        been hunting him. They want, nay need, that suit and will do nearly anything to get it.
      </notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
Lord Johnathan Clark
The floating city of Kent was a bastion of peace and honor. Rich in white jade mines and a
place of high learning. It was ruled over by the ruling house, Clark. Then came the ambitious
General, Xiao, a mercenary who gathered power wherever he could. In one swift stroke he wiped
out the Clark's and took control of the city. The Lord Clark was able to get his son secreted
away prior to the attack. Now Johnathan lives as an exile in Kausao City. He found an ancient
temple deep beneath the earth and there found the power to stand against Xiao and bullies like
him.

Portrayal: Champion of the People
Background: True King of Kent
Inciting Incident: House Destroyed, Family Dead
Belief: The Strong Must Protect the Weak
Trouble: I cannot Save Them All

Professons: Explorer(+3), Fighter and Aristocrat(+2), Scholar and Engineer(+1), Scoundrel(+0)

  Assets
  Device: Raiment of Rao
  In the hidden temple of Rao, buried deep beneath the City, Johnathan discovered an ancient
  Jadetech Power Suit. It is revolutionary and beyond what most alchemists are capable of even
  in this age of enlightenment. When in direct sunlight the suit allows the wearer to ride the
  beams of light and a degree of invulnerability. It is a strange mixture of Blue, Red and
  Black jade. Since he first stepped into the sky over Kausao, the rich and the criminal have
  been hunting him. They want, nay need, that suit and will do nearly anything to get it.

  Function Aspect: Ancient Power Suit
  Features: Exceptional(allows you tow fly, maneuver with explorer), Protective 2(reduce Shift
    Value of attacks against you by two), Sturdy 2(asset has 2 extra stress boxes)
  Flaws: Situational(only in direct sunlight), Troubling(everyone wants the suit's secrets

    Refresh: 1
-->

=== kbaird/Fate-XSLT/characters/Jadepunk/joker.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>The Laughing Man</charname>
    <playername>Jacob Possin</playername>
    <story>
A little over a year ago bodies began to show up on the riverfront. They seemed unrelated in
all ways, men, women, children, Naramel, Aerish, Kaiyumi, Túyangan, nothing connected them.
Nothing except the method of murder. Every one of the victims had bleached white skin and a
terrible smile on their faces.
<!--
During the first week seventeen bodies were found. Every week since, has had at least three
murders. The pressed dubbed this killer, "The Laughing Man." In the back alleys and along the
riverbanks, the stilt walkers and mudskimmers speak of a devil walking the midnight streets.
Strange shadows and maddened laughter are often heard, though none have ever seen him face to
face. In the last few months, The Laughing Man has begun to taunt the Watch, sending them
pieces of the victims and leaving random seeming notes.

If you walk the nighttime streets of the Riverfront, learn to walk in groups. And pray to
whatever gods will have you. Pray that you never meat the laughing man.
-->
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">The Smiling Killer</aspect>
    <aspect type="Background">A Mystery Even To Himself</aspect>
    <aspect type="Inciting-Incident">All It Takes Is One. Bad. Day.</aspect>
    <aspect type="Belief">Madness Is The Only Truth</aspect>
    <aspect type="Trouble">Murder On The Mind</aspect>
  </aspects>
  <professions>
    <profession rating="0" name="Aristocrat"/>
    <profession rating="2" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="1" name="Scholar"/>
    <profession rating="3" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="The Smiling Death" function="Black Jade Death Dust" type="Device">
      <features>
        <feature type="Harmful" bonus="4"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Must be close to The Laughing Man and must be breathed in"/>
      </flaws>
      <notes>
His victims are known by their rictus grin. He invented a black jade powder that, when inhaled,
causes hallucinations and death. Upon dying victims' faces stretch into a horrible grin and
their skin is drained of color.
      </notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
The Laughing Man
A little over a year ago bodies began to show up on the riverfront. They seemed unrelated in
all ways, men, women, children, Naramel, Aerish, Kaiyumi, Túyangan, nothing connected them.
Nothing except the method of murder. Every one of the victims had bleached white skin and a
terrible smile on their faces.

During the first week seventeen bodies were found. Every week since, has had at least three
murders. The pressed dubbed this killer, "The Laughing Man." In the back alleys and along the
riverbanks, the stilt walkers and mudskimmers speak of a devil walking the midnight streets.
Strange shadows and maddened laughter are often heard, though none have ever seen him face to
face. In the last few months, The Laughing Man has begun to taunt the Watch, sending them
pieces of the victims and leaving random seeming notes.

If you walk the nighttime streets of the Riverfront, learn to walk in groups. And pray to
whatever gods will have you. Pray that you never meat the laughing man.

Portrayal: The Smiling Killer
Background: A Mystery Even To Himself
Inciting Incident: All It Takes Is One. Bad. Day.
Belief: Madness Is The Only Truth
Trouble: Murder On The Mind

Professions: Scoundrel +3, Engineer and Fighting +2, Explorer and Scholar +1, Aristocrat +0

Assets
Device: The Smiling Death
His victims are known by their rictus grin. He invented a black jade powder that, when inhaled,
    causes hallucinations and death. Upon dying victims' faces stretch into a horrible grin and
    their skin is drained of color.

    Function Aspect: Black Jade Death Dust
    Features: Harmful 4(does four extra harm on a successful attack)
  Flaws: Situational(must be close to The Laughing Man and must breath it in)

  Refresh: 5(he is really lucky)
-->

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/johannes.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "Jadepunk/character.dtd">
<character>
  <id>
    <charname>Johannes van Coevorden</charname>
    <playername>Kevin Baird</playername>
    <story>&#160;</story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">&#160;</aspect>
    <aspect type="Background">Envoy for a Nottilan Commercial Concern</aspect>
    <aspect type="Inciting-Incident">&#160;</aspect>
    <aspect type="Belief">I'm Sure We Can Come to a Mutually Beneficial Understanding</aspect>
    <aspect type="Trouble">&#160;</aspect>
  </aspects>
  <professions>
    <profession rating="3" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="0" name="Fighter"/>
    <profession rating="2" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Cutting Remarks" guiding-aspect="Background" type="Technique">
      <features>
        <feature type="Exceptional" effect="Target may not check a Stress Box"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only for Attacks with Aristocrat"/>
      </flaws>
    </asset>
    <!--
    <asset name="Nottilan East Kausao Company" function="Corporate Family" type="Ally">
      <features>
        <feature type="Professional" bonus="2" main-profession="Aristocrat" other-professions="Scholar"/>
        <feature type="Numerous"     bonus="3"/>
        <feature type="Resilient"    bonus="1"/>
        <feature type="Independent"/>
        <feature type="Sturdy"       bonus="1"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only Business Concerns"/>
        <flaw type="Troubling"   effect="At Their Beck and Call"/>
      </flaws>
      <notes>I figure it's quite large, but the Numerous reflects a sub-group available to help at any given time.</notes>
    </asset>
    -->
    <asset name="Let's Make a Deal" guiding-aspect="Belief" type="Technique">
      <features>
        <feature type="Focus" bonus="2" profession="Aristocrat"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only to Create Advantages on an NPC who is someone else's boss"/>
      </flaws>
    </asset>
    <!--
    <asset name="Jade Tattoo" function="Blue Jade Tattoo of Detection" type="Device">
      <features>
        <feature bonus="3" type="Focus" profession="Scholar"/>
      </features>
      <flaws>
        <flaw type="Troubling"   effect="Easily Identifiable"/>
        <flaw type="Situational" effect="Scholar can only be used for sensing surroundings"/>
      </flaws>
      <notes>Obvious, like Mike Tyson's face tattoo, and IDs Đức as a 'Browncoat'.</notes>
    </asset>
    <asset name="Knowledge is Power" guiding-aspect="Inciting-Incident" type="Technique">
      <features>
        <feature type="Focus" profession="Scholar" bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only About Đạinamese, Túyàngan, or Kausaoan History"/>
      </flaws>
    </asset>
    -->
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/Jadepunk/aquaman.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Arthur, Lord of the Storm Sea</charname>
    <playername>Jacob Possin</playername>
    <story>
Python Mining Corporation is always looking for new ways to use jade, and new sources of jade.
twenty years back, someone in the company came to the conclusion that the ocean floor was an
untapped potential source of jade. Several development projects were started to deal with the
issues of mining the ocean floor. The Aquaman Project was one such.

<!--
The goal was to make a human worker able to survive in the ocean for great lengths of time.
They wanted to rebuild men into a slave race of jade miners at the bottom of the sea. The
experiment was both a greater success and a greater failure than they could have anticipated.
Their subject had phenomenal strength and endurance, could breath water, and even some sort of
empathic bond with ocean life. However, they could not break his spirit. One year ago, their
Aquaman destroyed the lab and ran away. Now they hunt him, seeking to take him apart and
rediscover what they lost in his escape.

Arthur has only vague memories of his life before the experiments. He remembers being cold and
hungry a lot. He remembers someone, maybe his mother, getting a large sum of money. He
remembers that he had to leave with the men this lady gave him to. That is all he remembers
from before. 15 years later he escaped. Arthur escaped the constant pain, the constant
experimentation. He escaped into a world he could barely understand. For the last year he has
been on the run from Python Mining, and the mercenaries they have hired to track him down.
During his time in the world he has helped many people. Fishermen and sea captains speak of the
Lord of the Storm Sea, a being of elemental power who brings the creatures of the sea to aid
foundering ships.
-->

Arthur has now arrived in Kausao after hearing of other people like him, the Jianghu. Hunted by
the authorities, he makes his way as a hero of the people. If you need help, and if you can
find him, maybe you can enlist the aid of the Aquaman.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Heart of the Ocean</aspect>
    <aspect type="Background">Escaped Experiment</aspect>
    <aspect type="Inciting-Incident">Never Again</aspect>
    <aspect type="Belief">People Must Be Free</aspect>
    <aspect type="Trouble">No Knowledge of the World of Men</aspect>
  </aspects>
  <professions>
    <profession rating="0" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="2" name="Explorer"/>
    <profession rating="3" name="Fighter"/>
    <profession rating="1" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Blue and White Jade Tattoos" function="Experimental Jade Tattoos" type="Device">
      <features>
        <feature type="Exceptional" effect="Does not need to breathe"/>
        <feature type="Protective" bonus="1"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only in water"/>
        <flaw type="Troubling"   effect="Hunted by the Python Mining Corporation"/>
      </flaws>
      <notes>
  These tattoos are of an intricate and archaic design. They allow the Aquaman to hold his breath
  indefinitly underwater (or nearly so) and withstand great pressure (the protective feature). They
  also had the side effect of allowing the Aquaman to exert some control over marine animal
  life (this falls under the allies, mechanically, but in fiction this is due to his tattoos) This
  design was the creation of a brilliant Jade Alchemist who died during Arthur's escape. These
  designs are the reason Python Mining is after him with such fervor.
      </notes>
    </asset>
    <asset name="The Fish of the Seas" function="Let My Armies be the Fish in the Sea" type="Ally">
      <features>
        <feature type="Independent"/>
        <feature type="Numerous" bonus="4"/>
        <feature type="Professional" bonus="1" main-profession="Fighter"/>
        <feature type="Resilient"/>
        <feature type="Resilient"/>
        <feature type="Sturdy"       bonus="2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only in water"/>
      </flaws>
      <notes>He controls marine life. This is kind of a lot of power.</notes>
    </asset>
  </assets>
  <consequences/>
</character>
<!--
Arthur, Lord of the Storm Sea
Python Mining Corporation is always looking for new ways to use jade, and new sources of jade.
twenty years back, someone in the company came to the conclusion that the ocean floor was an
untapped potential source of jade. Several development projects were started to deal with the
issues of mining the ocean floor. The Aquaman Project was one such.

The goal was to make a human worker able to survive in the ocean for great lengths of time.
They wanted to rebuild men into a slave race of jade miners at the bottom of the sea. The
experiment was both a greater success and a greater failure than they could have anticipated.
Their subject had phenomenal strength and endurance, could breath water, and even some sort of
empathic bond with ocean life. However, they could not break his spirit. One year ago, their
Aquaman destroyed the lab and ran away. Now they hunt him, seeking to take him apart and
rediscover what they lost in his escape.

Arthur has only vague memories of his life before the experiments. He remembers being cold and
hungry a lot. He remembers someone, maybe his mother, getting a large sum of money. He
remembers that he had to leave with the men this lady gave him to. That is all he remembers
from before. 15 years later he escaped. Arthur escaped the constant pain, the constant
experimentation. He escaped into a world he could barely understand. For the last year he has
been on the run from Python Mining, and the mercenaries they have hired to track him down.
During his time in the world he has helped many people. Fishermen and sea captains speak of the
Lord of the Storm Sea, a being of elemental power who brings the creatures of the sea to aid
foundering ships.

Arthur has now arrived in Kausao after hearing of other people like him, the Jianghu. Hunted by
the authorities, he makes his way as a hero of the people. If you need help, and if you can
find him, maybe you can enlist the aid of the Aquaman.

Portrayal: Heart Of The Ocean
Background: Escaped Experiment
Inciting Incident: Never Again
Belief: People Must Be Free
Trouble: No Knowledge Of The World Of Men

Professions: Fighting +3, Explorer and Scoundrel +2, Scholar and Engineer +1, Aristocrat +0

Assets
Device: Blue and White Jade tattoos
  These tattoos are of an intricate and archaic design. They allow the Aquaman to hold his breath
  indefinitly underwater(or nearly so) and withstand great pressure(the protective feature). They
  also had the side effect of allowing the Aquaman to exert some control over marine animal
  life(this falls under the allies, mechanically, but in fiction this is due to his tattoos) This
  design was the creation of a brilliant Jade Alchemist who died during Arthur's escape. These
  designs are the reason Python Mining is after him with such fervor.

  Function Aspect: Experimental Jade Tattoos
  Features: Protective 1(reduce shift value of attack against you by one), Exceptional(does not need to breath)
  Flaws: Troubling(hunted by the Python Mining Corporation), Situational(only in water)

Allies: The Fish of the Seas
  He controls marine life. This is kind of a lot of power.

  Function Aspect: Let My Armies Be The Fish In The Sea
  Features: Professional( Fighter +1), Resilient 2(two minor consequences), Sturdy 2(4 stress
    boxes), Independent, Numerous 4(16 critters at a time)
  Flaws: Situational(only in or near the water)


  Refresh 2
-->

=== kbaird/Fate-XSLT/characters/XiaoJiahuo/griff.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname nickname="Griff Lewelling">Gryffudd Llywellyn</charname>
    <playername>Brian Wilcox</playername>
    <story>
      &#160;
      Speaks Aerish natively; gets by for business purposes in Kaiyu, Túyàngan, and Naramel.
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Captain of the Airship [xxx]</aspect>
    <aspect type="Background">Self-Made Assassin</aspect>
    <aspect type="Inciting-Incident">"Friend" Let Mom Die</aspect>
    <aspect type="Belief">Death to the Rich</aspect>
    <aspect type="Trouble">[Vendetta / Dogma / Secrets]</aspect>
  </aspects>
  <professions>
    <profession rating="0" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="2" name="Explorer"/>
    <profession rating="2" name="Fighter"/>
    <profession rating="1" name="Scholar"/>
    <profession rating="3" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="[Ship Name]" function="White Jade Airship" type="Device">
      <features>
        <feature type="Aspect"      effect="Small and Manueverable"/>
        <feature type="Exceptional" effect="Instantly leave or appear in a scene, as long as there's a way in or out"/>
      </features>
      <flaws>
        <flaw type="Demanding" effect="Requires a Fair [+2] Explorer roll to get a ship underway"/>
        <flaw type="Consuming"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>

=== kbaird/Fate-XSLT/characters/Jadepunk/ben_urich.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE character SYSTEM "../Jadepunk/character.dtd">
<character>
  <id>
    <charname>Ben Urich</charname>
    <playername>adapted character</playername>
    <story>
      Old-school journalist, increasingly disgusted
    </story>
  </id>
  <refresh base="7"/>
  <aspects>
    <aspect type="Portrayal">Reporter Who's Seen It All</aspect>
    <aspect type="Background">My Wife is Very Ill</aspect>
    <aspect type="Inciting-Incident">I've Taken Them All Down</aspect>
    <aspect type="Belief">The Media Should Expose Corruption</aspect>
    <aspect type="Trouble">Easy To Find</aspect>
  </aspects>
  <professions>
    <profession rating="2" name="Aristocrat"/>
    <profession rating="1" name="Engineer"/>
    <profession rating="1" name="Explorer"/>
    <profession rating="0" name="Fighter"/>
    <profession rating="3" name="Scholar"/>
    <profession rating="2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset name="Ear to the Ground" guiding-aspect="Portrayal" type="Technique">
      <features>
        <feature type="Focus" profession="Aristocrat" bonus="4"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when using your network to find information"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>
