=== kbaird/Fate-XSLT/characters/Jadepunk/jadepunk.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, current-fate-points, aspects, professions, assets, consequences?, notes?)>

  <!ELEMENT id (charname, playername, story)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT story (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
  <!ELEMENT current-fate-points (#PCDATA)>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (Portrayal|Background|Inciting-Incident|Belief|Trouble) #REQUIRED>

  <!ELEMENT professions (profession*)>
    <!ELEMENT profession (#PCDATA)>
    <!ATTLIST profession name   CDATA #REQUIRED>
    <!ATTLIST profession rating CDATA #REQUIRED>

  <!ELEMENT assets (asset*)>
    <!ELEMENT asset (features*, flaws*)>
    <!ATTLIST asset cost           CDATA #REQUIRED>
    <!ATTLIST asset function       CDATA #IMPLIED>
    <!ATTLIST asset guiding-aspect CDATA #IMPLIED>
    <!ATTLIST asset name           CDATA #REQUIRED>
    <!ATTLIST asset type           CDATA #REQUIRED>

    <!ELEMENT features (feature*)>
      <!ELEMENT feature (#PCDATA)>
      <!ATTLIST feature effect CDATA #IMPLIED>
      <!ATTLIST feature type
        (Aspect|Exceptional|Flexible|Focus|Harmful|Independent|Numerous|Professional|Protective|Resilient|Sturdy|Talented)
      #REQUIRED>

    <!ELEMENT flaws (flaw*)>
      <!ELEMENT flaw (#PCDATA)>
      <!ATTLIST flaw effect CDATA #IMPLIED>
      <!ATTLIST flaw type (Consuming|Demanding|Limited|Situational|Troubling) #REQUIRED>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

  <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/taia_kwan.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../xslt/jadepunk_html.xsl"?>
<!DOCTYPE jadepunk SYSTEM "../jadepunk.dtd">
<character>
 <id>
  <charname>Taia Kwan</charname>
  <playername>sample Jadepunk character</playername>
  <story>
   When Taia was a young girl she witnessed a martial arts duel. Inspired by
   what she saw, she has dedicated her life to the mastery of the martial arts,
   illegal or not. The Governor be damned.
  </story>
 </id>
 <refresh>3</refresh>
 <current-fate-points>3</current-fate-points>
 <aspects>
  <aspect type="Portrayal">Youthful Martial Arts Master</aspect>
  <aspect type="Background">I Grew Up On the Streets of Kausao City</aspect>
  <aspect type="Inciting-Incident">Witnessed a Martial Arts Duel</aspect>
  <aspect type="Belief">I Have Sacrificed Too Much to Stop Now</aspect>
  <aspect type="Trouble">Never Able to Cut Loose</aspect>
 </aspects>
 <professions>
  <profession rating="0" name="Aristocrat"/>
  <profession rating="1" name="Engineer"/>
  <profession rating="2" name="Explorer"/>
  <profession rating="3" name="Fighter"/>
  <profession rating="1" name="Scholar"/>
  <profession rating="2" name="Scoundrel"/>
 </professions>
 <assets>
  <asset cost="2" function="Green Jade Tattoo of Protection" name="Jade Tattoo" type="Device">
   <features>
    <feature effect="1" type="Protective"/>
    <feature effect="2" type="Sturdy"/>
   </features>
   <flaws>
    <flaw type="Troubling" effect="Easily Identifiable"/>
   </flaws>
  </asset>
  <asset cost="1" function="My Mentor's Sword" name="Jian Longsword" type="Device">
   <features>
    <feature effect="2" type="Harmful"/>
   </features>
   <flaws>
    <flaw type="Troubling" effect="It's Illegal to Own a Guardsman's Blade"/>
   </flaws>
  </asset>
  <asset cost="1" guiding-aspect="Portrayal" name="Jirai Mastery" type="Technique">
   <features>
    <feature type="Focus" effect="Fighter +2"/>
   </features>
   <flaws>
    <flaw type="Situational" effect="Only When Wielding a Jian Longsword"/>
   </flaws>
  </asset>
 </assets>
 <consequences>
  <consequence severity="Mild">mild one</consequence>
 </consequences>
</character>

=== kbaird/Fate-XSLT/characters/Jadepunk/jaron_reis.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/jadepunk_html.xsl"?>
<!DOCTYPE jadepunk SYSTEM "jadepunk.dtd">
<character>
  <id>
    <charname>Jaron Reis</charname>
    <playername>sample Jadepunk character</playername>
    <story>
      Jaron murdered a man to get his position on the Council, giving him a bad
      reputation and a lot of guilt. He has since joined the Jianghu (江湖; lit.
      "rivers and lakes"), and uses his resources and power to assist them.
    </story>
  </id>
  <refresh>3</refresh>
  <current-fate-points>3</current-fate-points>
  <aspects>
    <aspect type="Portrayal">Councilor of the 江湖</aspect>
    <aspect type="Background">Naramel Representative on the Council of Nine</aspect>
    <aspect type="Inciting-Incident">Committed Murder in the Name of the Council</aspect>
    <aspect type="Belief">No One Should Have Absolute Power</aspect>
    <aspect type="Trouble">Secretly in Debt</aspect>
  </aspects>
  <professions>
    <profession rating="+3" name="Aristocrat"/>
    <profession rating="+1" name="Engineer"/>
    <profession rating="+1" name="Explorer"/>
    <profession rating="0" name="Fighter"/>
    <profession rating="+2" name="Scholar"/>
    <profession rating="+2" name="Scoundrel"/>
  </professions>
  <assets>
    <asset cost="2" function="White Jade Airship" name="Airship" type="Device">
      <features>
        <feature type="Aspect" effect="江湖 crew"/>
        <feature type="Exceptional" effect="Instantly leave or appear in a scene, as long as there's a way in or out"/>
      </features>
      <flaws>
        <flaw type="Consuming"/>
        <flaw type="Demanding" effect="Requires a Fair [+2] Explorer roll to get a ship underway"/>
      </flaws>
    </asset>
    <asset cost="1" guiding-aspect="Background" name="Councilor's Perks" type="Technique">
      <features>
        <feature type="Flexible" effect="Roll Aristocrat instead of Engineer"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when creating temporary Device assets"/>
      </flaws>
    </asset>
    <asset cost="1" guiding-aspect="Portrayal" name="Ear to the Ground" type="Technique">
      <features>
        <feature type="Focus" effect="Aristocrat +2"/>
      </features>
      <flaws>
        <flaw type="Situational" effect="Only when using your network to find information"/>
      </flaws>
    </asset>
  </assets>
  <consequences/>
</character>
