=== kbaird/Fate-XSLT/characters/FateAccelerated/npc.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT npc (id, aspects, skilled-at, bad-at, stress)>

  <!ELEMENT id (charname, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type CDATA #IMPLIED>

  <!ELEMENT skilled-at (#PCDATA)>

  <!ELEMENT bad-at (#PCDATA)>

  <!ELEMENT stress (#PCDATA)>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/isolationists.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fae_npc_md.xsl"?>
<!DOCTYPE character SYSTEM "../FateAccelerated/npc.dtd">
<npc>
  <id>
    <name>Isolationists</name>
    <description>We don't much care for outsiders. It's kind of our thing. Imagine Asimov's Mycogenians from Prelude to Foundation.</description>
  </id>
  <aspects>
    <aspect>Inscrutable Separatists</aspect>
    <aspect>Vulnerable Belly</aspect>
  </aspects>
  <skilled-at>Scowling and Being Stubborn</skilled-at>
  <bad-at>Deft Social Interactions</bad-at>
  <stress>2</stress>
</npc>
